import type { CharterNodeDef } from './charter';

/** Authored terms for the eight expanded Drainage Charter wings. */
export const WING_NODES: CharterNodeDef[] = [
  {
    id: 'roots-1-1',
    name: 'Water Table I',
    emoji: '🌿',
    description: 'Holds the low ground against another dry season.',
    branch: 'roots',
    cost: 2,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 1.25 }],
  },
  {
    id: 'roots-1-2',
    name: 'Water Table II',
    emoji: '🌿',
    description: 'Marks the channels where clean peat can still be lifted.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-1',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 1.5 }],
  },
  {
    id: 'roots-1-3',
    name: 'Water Table III',
    emoji: '🌿',
    description: 'Keeps the harvesters from arguing with the waterline.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-1-2',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 2 }],
  },
  {
    id: 'roots-1-4',
    name: 'Water Table IV',
    emoji: '🌿',
    description: 'Puts a firm boundary around the wettest beds.',
    branch: 'roots',
    cost: 8,
    requires: 'roots-1-3',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 3 }],
  },
  {
    id: 'roots-1-5',
    name: 'Water Table V',
    emoji: '🌿',
    description: 'Turns standing water into a patient reserve.',
    branch: 'roots',
    cost: 13,
    requires: 'roots-1-4',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 5 }],
  },
  {
    id: 'roots-1-6',
    name: 'Water Table VI',
    emoji: '🌿',
    description: 'Leaves the whole basin better than the survey found it.',
    branch: 'roots',
    cost: 21,
    requires: 'roots-1-5',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 7 }],
  },
  {
    id: 'roots-1-leaf-1',
    name: 'Sluice Witness',
    emoji: '🌿',
    description: 'Keeps the sluice book honest when the rain arrives.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 2 }],
  },
  {
    id: 'roots-1-leaf-2',
    name: 'Tussock Key',
    emoji: '🌿',
    description: 'Opens a dry path through ground that prefers to close.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 3 }],
  },
  {
    id: 'roots-1-leaf-3',
    name: 'Fen Boundary',
    emoji: '🌿',
    description: 'Settles the boundary dispute without moving a single marker.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'roots-2-1',
    name: 'Tussock Memory I',
    emoji: '🌿',
    description: 'Keeps a pressed copy of every useful green surface.',
    branch: 'roots',
    cost: 4,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 1.25 }],
  },
  {
    id: 'roots-2-2',
    name: 'Tussock Memory II',
    emoji: '🌿',
    description: 'Teaches the cutters which moss will spring back overnight.',
    branch: 'roots',
    cost: 6,
    requires: 'roots-2-1',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 1.5 }],
  },
  {
    id: 'roots-2-3',
    name: 'Tussock Memory III',
    emoji: '🌿',
    description: 'Stores the bogs older answers under fresh growth.',
    branch: 'roots',
    cost: 10,
    requires: 'roots-2-2',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 2 }],
  },
  {
    id: 'roots-2-4',
    name: 'Tussock Memory IV',
    emoji: '🌿',
    description: 'Makes soft ground count as a reliable witness.',
    branch: 'roots',
    cost: 16,
    requires: 'roots-2-3',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 3 }],
  },
  {
    id: 'roots-2-5',
    name: 'Tussock Memory V',
    emoji: '🌿',
    description: 'Lets the harvest borrow strength from last years rain.',
    branch: 'roots',
    cost: 26,
    requires: 'roots-2-4',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 5 }],
  },
  {
    id: 'roots-2-6',
    name: 'Tussock Memory VI',
    emoji: '🌿',
    description: 'Returns the whole tussock field to its proper account.',
    branch: 'roots',
    cost: 42,
    requires: 'roots-2-5',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 7 }],
  },
  {
    id: 'roots-2-leaf-1',
    name: 'Moss Witness',
    emoji: '🌿',
    description: 'Signs for a harvest the court would otherwise lose.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-2-6',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 2 }],
  },
  {
    id: 'roots-2-leaf-2',
    name: 'Green Margin',
    emoji: '🌿',
    description: 'Leaves one careful margin for the next growth cycle.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-2-6',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 3 }],
  },
  {
    id: 'roots-3-1',
    name: 'Waterlogged Archive I',
    emoji: '🌿',
    description: 'Keeps old drainage maps legible beneath the brown water.',
    branch: 'roots',
    cost: 6,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 1.25 }],
  },
  {
    id: 'roots-3-2',
    name: 'Waterlogged Archive II',
    emoji: '🌿',
    description: 'Finds the useful paragraph in a sodden record.',
    branch: 'roots',
    cost: 10,
    requires: 'roots-3-1',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 1.5 }],
  },
  {
    id: 'roots-3-3',
    name: 'Waterlogged Archive III',
    emoji: '🌿',
    description: 'Teaches the docket which scraps of evidence still float.',
    branch: 'roots',
    cost: 15,
    requires: 'roots-3-2',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 2 }],
  },
  {
    id: 'roots-3-4',
    name: 'Waterlogged Archive IV',
    emoji: '🌿',
    description: 'Makes a wet archive serve a dry calculation.',
    branch: 'roots',
    cost: 25,
    requires: 'roots-3-3',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 3 }],
  },
  {
    id: 'roots-3-5',
    name: 'Waterlogged Archive V',
    emoji: '🌿',
    description: 'Binds the surviving pages into a working ledger.',
    branch: 'roots',
    cost: 39,
    requires: 'roots-3-4',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 5 }],
  },
  {
    id: 'roots-3-6',
    name: 'Waterlogged Archive VI',
    emoji: '🌿',
    description: 'Gives the bog a memory that no flood can amend.',
    branch: 'roots',
    cost: 63,
    requires: 'roots-3-5',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 7 }],
  },
  {
    id: 'roots-3-leaf-1',
    name: 'Flooded Index',
    emoji: '🌿',
    description: 'Puts the submerged records back in alphabetical order.',
    branch: 'roots',
    cost: 7,
    requires: 'roots-3-6',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 2 }],
  },
  {
    id: 'roots-3-leaf-2',
    name: 'Sodden Exhibit',
    emoji: '🌿',
    description: 'Admits one damp exhibit and finds it surprisingly useful.',
    branch: 'roots',
    cost: 7,
    requires: 'roots-3-6',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 3 }],
  },
  {
    id: 'roots-4-1',
    name: 'Peat Inheritance I',
    emoji: '🌿',
    description: 'Passes the first good habit from one run to the next.',
    branch: 'roots',
    cost: 8,
    requires: 'roots-4',
    effects: [{ kind: 'startingBroth', amount: 100 }],
  },
  {
    id: 'roots-4-2',
    name: 'Peat Inheritance II',
    emoji: '🌿',
    description: 'Leaves the cutters a little broth before the gates open.',
    branch: 'roots',
    cost: 13,
    requires: 'roots-4-1',
    effects: [{ kind: 'startingBroth', amount: 250 }],
  },
  {
    id: 'roots-4-3',
    name: 'Peat Inheritance III',
    emoji: '🌿',
    description: 'Teaches a drained bog to begin with something in reserve.',
    branch: 'roots',
    cost: 20,
    requires: 'roots-4-2',
    effects: [{ kind: 'startingBroth', amount: 500 }],
  },
  {
    id: 'roots-4-4',
    name: 'Peat Inheritance IV',
    emoji: '🌿',
    description: 'Keeps the familys useful mistakes out of the new ledger.',
    branch: 'roots',
    cost: 33,
    requires: 'roots-4-3',
    effects: [{ kind: 'startingBroth', amount: 1000 }],
  },
  {
    id: 'roots-4-5',
    name: 'Peat Inheritance V',
    emoji: '🌿',
    description: 'Makes every return feel less like starting over.',
    branch: 'roots',
    cost: 52,
    requires: 'roots-4-4',
    effects: [{ kind: 'startingBroth', amount: 2000 }],
  },
  {
    id: 'roots-4-6',
    name: 'Peat Inheritance VI',
    emoji: '🌿',
    description: 'Hands the next run an inheritance the court cannot tax.',
    branch: 'roots',
    cost: 84,
    requires: 'roots-4-5',
    effects: [{ kind: 'startingBroth', amount: 4000 }],
  },
  {
    id: 'roots-4-leaf-1',
    name: 'Inherited Spade',
    emoji: '🌿',
    description: 'Sets a spare spade beside the first empty trench.',
    branch: 'roots',
    cost: 9,
    requires: 'roots-4-6',
    effects: [{ kind: 'startingBroth', amount: 500 }],
  },
  {
    id: 'roots-4-leaf-2',
    name: 'Heirloom Sump',
    emoji: '🌿',
    description: 'Keeps one useful sump waiting through the reset.',
    branch: 'roots',
    cost: 9,
    requires: 'roots-4-6',
    effects: [{ kind: 'startingBroth', amount: 1000 }],
  },
  {
    id: 'roots-capstone-1',
    name: 'Greenwater Concord',
    emoji: '🌿',
    description: 'Joins the root records into one settlement the bog will honour.',
    branch: 'roots',
    cost: 650,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'peat', factor: 7 }],
  },
  {
    id: 'roots-capstone-2',
    name: 'Inheritance Writ',
    emoji: '🌿',
    description: 'Makes old growth admissible in every future proceeding.',
    branch: 'roots',
    cost: 725,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 7 }],
  },
  {
    id: 'roots-capstone-3',
    name: 'Basin Memory',
    emoji: '🌿',
    description: 'Closes the roots ledger with no useful habit left unsigned.',
    branch: 'roots',
    cost: 800,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'all', factor: 1.5 }],
  },
  {
    id: 'kindling-1-1',
    name: 'Boiler Practice I',
    emoji: '🔥',
    description: 'Keeps the first flame below the threshold of complaint.',
    branch: 'kindling',
    cost: 2,
    requires: 'kindling-4',
    effects: [{ kind: 'heat', factor: 0.98 }],
  },
  {
    id: 'kindling-1-2',
    name: 'Boiler Practice II',
    emoji: '🔥',
    description: 'Teaches the boiler to waste less heat on the rafters.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-1',
    effects: [{ kind: 'heat', factor: 0.96 }],
  },
  {
    id: 'kindling-1-3',
    name: 'Boiler Practice III',
    emoji: '🔥',
    description: 'Makes a warm rack answer to a cooler order.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-1-2',
    effects: [{ kind: 'heat', factor: 0.94 }],
  },
  {
    id: 'kindling-1-4',
    name: 'Boiler Practice IV',
    emoji: '🔥',
    description: 'Puts every flare on a schedule the clerk can read.',
    branch: 'kindling',
    cost: 8,
    requires: 'kindling-1-3',
    effects: [{ kind: 'heat', factor: 0.92 }],
  },
  {
    id: 'kindling-1-5',
    name: 'Boiler Practice V',
    emoji: '🔥',
    description: 'Turns excess heat into a signed procedural error.',
    branch: 'kindling',
    cost: 13,
    requires: 'kindling-1-4',
    effects: [{ kind: 'heat', factor: 0.9 }],
  },
  {
    id: 'kindling-1-6',
    name: 'Boiler Practice VI',
    emoji: '🔥',
    description: 'Leaves the whole boiler room running hot but civil.',
    branch: 'kindling',
    cost: 21,
    requires: 'kindling-1-5',
    effects: [{ kind: 'heat', factor: 0.88 }],
  },
  {
    id: 'kindling-1-leaf-1',
    name: 'Quiet Flue',
    emoji: '🔥',
    description: 'Lets one stubborn flue carry its heat without shouting.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.90 }],
  },
  {
    id: 'kindling-1-leaf-2',
    name: 'Boiler Margin',
    emoji: '🔥',
    description: 'Reserves a little room beneath the red line.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.88 }],
  },
  {
    id: 'kindling-1-leaf-3',
    name: 'Ash Ruling',
    emoji: '🔥',
    description: 'Records the ash as evidence rather than waste.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.92 }],
  },
  {
    id: 'kindling-2-1',
    name: 'Methane Docket I',
    emoji: '🔥',
    description: 'Puts the gas on the record before it wanders off.',
    branch: 'kindling',
    cost: 4,
    requires: 'kindling-4',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 1.25 }],
  },
  {
    id: 'kindling-2-2',
    name: 'Methane Docket II',
    emoji: '🔥',
    description: 'Makes a methane bloom answer the same question twice.',
    branch: 'kindling',
    cost: 6,
    requires: 'kindling-2-1',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 1.5 }],
  },
  {
    id: 'kindling-2-3',
    name: 'Methane Docket III',
    emoji: '🔥',
    description: 'Keeps the rising pressure useful instead of dramatic.',
    branch: 'kindling',
    cost: 10,
    requires: 'kindling-2-2',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 2 }],
  },
  {
    id: 'kindling-2-4',
    name: 'Methane Docket IV',
    emoji: '🔥',
    description: 'Turns a suspicious hiss into a dependable supply.',
    branch: 'kindling',
    cost: 16,
    requires: 'kindling-2-3',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 3 }],
  },
  {
    id: 'kindling-2-5',
    name: 'Methane Docket V',
    emoji: '🔥',
    description: 'Gives the gas line a witness and a timetable.',
    branch: 'kindling',
    cost: 26,
    requires: 'kindling-2-4',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 5 }],
  },
  {
    id: 'kindling-2-6',
    name: 'Methane Docket VI',
    emoji: '🔥',
    description: 'Lets the whole methane docket speak at full volume.',
    branch: 'kindling',
    cost: 42,
    requires: 'kindling-2-5',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 7 }],
  },
  {
    id: 'kindling-2-leaf-1',
    name: 'Gas Affidavit',
    emoji: '🔥',
    description: 'Gets the gas to swear it was present all along.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-2-6',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 3 }],
  },
  {
    id: 'kindling-2-leaf-2',
    name: 'Rising Clause',
    emoji: '🔥',
    description: 'Adds a clause for pressure that refuses to wait.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-2-6',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 5 }],
  },
  {
    id: 'kindling-3-1',
    name: 'Rack Ember I',
    emoji: '🔥',
    description: 'Keeps one ember where the compute racks can reach it.',
    branch: 'kindling',
    cost: 6,
    requires: 'kindling-4',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 1.25 }],
  },
  {
    id: 'kindling-3-2',
    name: 'Rack Ember II',
    emoji: '🔥',
    description: 'Makes the rack room take a faster but tidier breath.',
    branch: 'kindling',
    cost: 10,
    requires: 'kindling-3-1',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 1.5 }],
  },
  {
    id: 'kindling-3-3',
    name: 'Rack Ember III',
    emoji: '🔥',
    description: 'Turns a stray spark into a useful compute allowance.',
    branch: 'kindling',
    cost: 15,
    requires: 'kindling-3-2',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 2 }],
  },
  {
    id: 'kindling-3-4',
    name: 'Rack Ember IV',
    emoji: '🔥',
    description: 'Lets every warm shelf carry its share of the verdict.',
    branch: 'kindling',
    cost: 25,
    requires: 'kindling-3-3',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 3 }],
  },
  {
    id: 'kindling-3-5',
    name: 'Rack Ember V',
    emoji: '🔥',
    description: 'Gives the racks enough ember to finish the argument.',
    branch: 'kindling',
    cost: 39,
    requires: 'kindling-3-4',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 5 }],
  },
  {
    id: 'kindling-3-6',
    name: 'Rack Ember VI',
    emoji: '🔥',
    description: 'Sets the entire compute room alight without burning the docket.',
    branch: 'kindling',
    cost: 63,
    requires: 'kindling-3-5',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 7 }],
  },
  {
    id: 'kindling-3-leaf-1',
    name: 'Rack Spark',
    emoji: '🔥',
    description: 'Keeps a small spark under every working shelf.',
    branch: 'kindling',
    cost: 7,
    requires: 'kindling-3-6',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 3 }],
  },
  {
    id: 'kindling-3-leaf-2',
    name: 'Hot Verdict',
    emoji: '🔥',
    description: 'Delivers the ruling before the cooling clerk objects.',
    branch: 'kindling',
    cost: 7,
    requires: 'kindling-3-6',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 5 }],
  },
  {
    id: 'kindling-4-1',
    name: 'Verdict Spark I',
    emoji: '🔥',
    description: 'Moves the research docket before the first kettle boils.',
    branch: 'kindling',
    cost: 8,
    requires: 'kindling-4',
    effects: [{ kind: 'researchSpeed', factor: 1.05 }],
  },
  {
    id: 'kindling-4-2',
    name: 'Verdict Spark II',
    emoji: '🔥',
    description: 'Gives the clerks a lamp bright enough for another page.',
    branch: 'kindling',
    cost: 13,
    requires: 'kindling-4-1',
    effects: [{ kind: 'researchSpeed', factor: 1.1 }],
  },
  {
    id: 'kindling-4-3',
    name: 'Verdict Spark III',
    emoji: '🔥',
    description: 'Makes a second reading feel less like a delay.',
    branch: 'kindling',
    cost: 20,
    requires: 'kindling-4-2',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'kindling-4-4',
    name: 'Verdict Spark IV',
    emoji: '🔥',
    description: 'Puts the useful result at the top of the stack.',
    branch: 'kindling',
    cost: 33,
    requires: 'kindling-4-3',
    effects: [{ kind: 'researchSpeed', factor: 1.3 }],
  },
  {
    id: 'kindling-4-5',
    name: 'Verdict Spark V',
    emoji: '🔥',
    description: 'Turns a long review into a brisk administrative matter.',
    branch: 'kindling',
    cost: 52,
    requires: 'kindling-4-4',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'kindling-4-6',
    name: 'Verdict Spark VI',
    emoji: '🔥',
    description: 'Lets the whole research bench reach its conclusion early.',
    branch: 'kindling',
    cost: 84,
    requires: 'kindling-4-5',
    effects: [{ kind: 'researchSpeed', factor: 1.5 }],
  },
  {
    id: 'kindling-4-leaf-1',
    name: 'Prompt Finding',
    emoji: '🔥',
    description: 'Finds the answer in the margin before the hearing begins.',
    branch: 'kindling',
    cost: 9,
    requires: 'kindling-4-6',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'kindling-4-leaf-2',
    name: 'Early Ruling',
    emoji: '🔥',
    description: 'Places a useful ruling where the researchers can reach it.',
    branch: 'kindling',
    cost: 9,
    requires: 'kindling-4-6',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'kindling-capstone-1',
    name: 'Boiler Sentence',
    emoji: '🔥',
    description: 'Makes the heat ledger answer for every careless flame.',
    branch: 'kindling',
    cost: 650,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'heat', factor: 0.80 }],
  },
  {
    id: 'kindling-capstone-2',
    name: 'Methane Verdict',
    emoji: '🔥',
    description: 'Gives the gas a final ruling and a larger room to rise in.',
    branch: 'kindling',
    cost: 725,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'multiplier', target: 'methane', factor: 7 }],
  },
  {
    id: 'kindling-capstone-3',
    name: 'Ember Precedent',
    emoji: '🔥',
    description: 'Sets a bright precedent for every rack that follows.',
    branch: 'kindling',
    cost: 800,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'multiplier', target: 'compute', factor: 7 }],
  },
  {
    id: 'filing-1-1',
    name: 'Night Docket I',
    emoji: '🕯️',
    description: 'Keeps the evening docket open past the sensible hour.',
    branch: 'filing',
    cost: 2,
    requires: 'filing-4',
    effects: [{ kind: 'offlineRate', add: 0.01 }],
  },
  {
    id: 'filing-1-2',
    name: 'Night Docket II',
    emoji: '🕯️',
    description: 'Lets one more filing cross the desk before dawn.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-1',
    effects: [{ kind: 'offlineRate', add: 0.02 }],
  },
  {
    id: 'filing-1-3',
    name: 'Night Docket III',
    emoji: '🕯️',
    description: 'Makes the night clerk less dependent on daylight.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-1-2',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'filing-1-4',
    name: 'Night Docket IV',
    emoji: '🕯️',
    description: 'Turns late work into a standing administrative habit.',
    branch: 'filing',
    cost: 8,
    requires: 'filing-1-3',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'filing-1-5',
    name: 'Night Docket V',
    emoji: '🕯️',
    description: 'Keeps every after-hours page moving through the room.',
    branch: 'filing',
    cost: 13,
    requires: 'filing-1-4',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'filing-1-6',
    name: 'Night Docket VI',
    emoji: '🕯️',
    description: 'Gives the dark a full and properly indexed docket.',
    branch: 'filing',
    cost: 21,
    requires: 'filing-1-5',
    effects: [{ kind: 'offlineRate', add: 0.06 }],
  },
  {
    id: 'filing-1-leaf-1',
    name: 'Afterhours Stamp',
    emoji: '🕯️',
    description: 'Puts a quiet stamp on work done after closing.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'filing-1-leaf-2',
    name: 'Midnight Seal',
    emoji: '🕯️',
    description: 'Keeps the last seal warm until the morning shift.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'filing-1-leaf-3',
    name: 'Late Filing',
    emoji: '🕯️',
    description: 'Accepts one more filing without waking the Magistrate.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'filing-2-1',
    name: 'Clerk Circuit I',
    emoji: '🕯️',
    description: 'Keeps the clerk moving between lamps without losing the thread.',
    branch: 'filing',
    cost: 4,
    requires: 'filing-4',
    effects: [{ kind: 'offlineRate', add: 0.015 }],
  },
  {
    id: 'filing-2-2',
    name: 'Clerk Circuit II',
    emoji: '🕯️',
    description: 'Adds another reliable circuit to the late-night office.',
    branch: 'filing',
    cost: 6,
    requires: 'filing-2-1',
    effects: [{ kind: 'offlineRate', add: 0.025 }],
  },
  {
    id: 'filing-2-3',
    name: 'Clerk Circuit III',
    emoji: '🕯️',
    description: 'Makes every dark corridor part of the same ledger.',
    branch: 'filing',
    cost: 10,
    requires: 'filing-2-2',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'filing-2-4',
    name: 'Clerk Circuit IV',
    emoji: '🕯️',
    description: 'Lets a careful clerk carry two dockets at once.',
    branch: 'filing',
    cost: 16,
    requires: 'filing-2-3',
    effects: [{ kind: 'offlineRate', add: 0.045 }],
  },
  {
    id: 'filing-2-5',
    name: 'Clerk Circuit V',
    emoji: '🕯️',
    description: 'Puts the whole circuit under a single night order.',
    branch: 'filing',
    cost: 26,
    requires: 'filing-2-4',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'filing-2-6',
    name: 'Clerk Circuit VI',
    emoji: '🕯️',
    description: 'Keeps the filing room working when the bog goes quiet.',
    branch: 'filing',
    cost: 42,
    requires: 'filing-2-5',
    effects: [{ kind: 'offlineRate', add: 0.065 }],
  },
  {
    id: 'filing-2-leaf-1',
    name: 'Second Circuit',
    emoji: '🕯️',
    description: 'Adds a second circuit where the first one tired.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-2-6',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'filing-2-leaf-2',
    name: 'Clerk Relay',
    emoji: '🕯️',
    description: 'Passes the ledger to a clerk who was already waiting.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-2-6',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'filing-3-1',
    name: 'Away Record I',
    emoji: '🕯️',
    description: 'Keeps a clean record of the hours nobody witnessed.',
    branch: 'filing',
    cost: 6,
    requires: 'filing-4',
    effects: [{ kind: 'offlineCap', addSeconds: 1800 }],
  },
  {
    id: 'filing-3-2',
    name: 'Away Record II',
    emoji: '🕯️',
    description: 'Adds another page to the archive of unattended work.',
    branch: 'filing',
    cost: 10,
    requires: 'filing-3-1',
    effects: [{ kind: 'offlineCap', addSeconds: 3600 }],
  },
  {
    id: 'filing-3-3',
    name: 'Away Record III',
    emoji: '🕯️',
    description: 'Makes absence count as a modest form of supervision.',
    branch: 'filing',
    cost: 15,
    requires: 'filing-3-2',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'filing-3-4',
    name: 'Away Record IV',
    emoji: '🕯️',
    description: 'Lets the ledger remember what happened while doors were shut.',
    branch: 'filing',
    cost: 25,
    requires: 'filing-3-3',
    effects: [{ kind: 'offlineCap', addSeconds: 10800 }],
  },
  {
    id: 'filing-3-5',
    name: 'Away Record V',
    emoji: '🕯️',
    description: 'Keeps the away record open through a longer silence.',
    branch: 'filing',
    cost: 39,
    requires: 'filing-3-4',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'filing-3-6',
    name: 'Away Record VI',
    emoji: '🕯️',
    description: 'Turns unattended hours into a respectable institutional memory.',
    branch: 'filing',
    cost: 63,
    requires: 'filing-3-5',
    effects: [{ kind: 'offlineCap', addSeconds: 21600 }],
  },
  {
    id: 'filing-3-leaf-1',
    name: 'Extended Docket',
    emoji: '🕯️',
    description: 'Leaves the docket open for one more useful interval.',
    branch: 'filing',
    cost: 7,
    requires: 'filing-3-6',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'filing-3-leaf-2',
    name: 'Long Adjournment',
    emoji: '🕯️',
    description: 'Makes an adjournment long enough to be worth recording.',
    branch: 'filing',
    cost: 7,
    requires: 'filing-3-6',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'filing-4-1',
    name: 'Lamp Continuance I',
    emoji: '🕯️',
    description: 'Keeps the lamps lit without pretending the court is awake.',
    branch: 'filing',
    cost: 8,
    requires: 'filing-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.1 }],
  },
  {
    id: 'filing-4-2',
    name: 'Lamp Continuance II',
    emoji: '🕯️',
    description: 'Makes unattended production a little less apologetic.',
    branch: 'filing',
    cost: 13,
    requires: 'filing-4-1',
    effects: [{ kind: 'offlineMultiplier', factor: 1.2 }],
  },
  {
    id: 'filing-4-3',
    name: 'Lamp Continuance III',
    emoji: '🕯️',
    description: 'Lets the night office keep more of what it starts.',
    branch: 'filing',
    cost: 20,
    requires: 'filing-4-2',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'filing-4-4',
    name: 'Lamp Continuance IV',
    emoji: '🕯️',
    description: 'Turns a dim continuation into a dependable one.',
    branch: 'filing',
    cost: 33,
    requires: 'filing-4-3',
    effects: [{ kind: 'offlineMultiplier', factor: 1.4 }],
  },
  {
    id: 'filing-4-5',
    name: 'Lamp Continuance V',
    emoji: '🕯️',
    description: 'Gives the lamps enough patience for a full absence.',
    branch: 'filing',
    cost: 52,
    requires: 'filing-4-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'filing-4-6',
    name: 'Lamp Continuance VI',
    emoji: '🕯️',
    description: 'Keeps the whole night court bright at its quietest.',
    branch: 'filing',
    cost: 84,
    requires: 'filing-4-5',
    effects: [{ kind: 'offlineMultiplier', factor: 1.6 }],
  },
  {
    id: 'filing-4-leaf-1',
    name: 'Quiet Continuance',
    emoji: '🕯️',
    description: 'Continues the work quietly and returns a little more of it.',
    branch: 'filing',
    cost: 9,
    requires: 'filing-4-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'filing-4-leaf-2',
    name: 'Closed Court Yield',
    emoji: '🕯️',
    description: 'Lets the closed court keep its best unfinished business.',
    branch: 'filing',
    cost: 9,
    requires: 'filing-4-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'filing-capstone-1',
    name: 'Nocturne Filing',
    emoji: '🕯️',
    description: 'Keeps every useful night entry together under one dark cover.',
    branch: 'filing',
    cost: 650,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineRate', add: 0.08 }],
  },
  {
    id: 'filing-capstone-2',
    name: 'Clerk of Last Light',
    emoji: '🕯️',
    description: 'Appoints the last lamp to a post it cannot abandon.',
    branch: 'filing',
    cost: 725,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineMultiplier', factor: 1.8 }],
  },
  {
    id: 'filing-capstone-3',
    name: 'Adjournment Without End',
    emoji: '🕯️',
    description: 'Extends the quiet work until the bog itself objects.',
    branch: 'filing',
    cost: 800,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineCap', addSeconds: 43200 }],
  },
  {
    id: 'hands-1-1',
    name: 'Copper Grip I',
    emoji: '🖐️',
    description: 'Teaches the thumb where the harvest button gives way.',
    branch: 'hands',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'click', factor: 1.25 }],
  },
  {
    id: 'hands-1-2',
    name: 'Copper Grip II',
    emoji: '🖐️',
    description: 'Turns a firm grip into a reliable measure of broth.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-1',
    effects: [{ kind: 'multiplier', target: 'click', factor: 1.5 }],
  },
  {
    id: 'hands-1-3',
    name: 'Copper Grip III',
    emoji: '🖐️',
    description: 'Keeps the hand steady through a long morning of clicks.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-1-2',
    effects: [{ kind: 'multiplier', target: 'click', factor: 2 }],
  },
  {
    id: 'hands-1-4',
    name: 'Copper Grip IV',
    emoji: '🖐️',
    description: 'Makes each press land with the weight of a signed instruction.',
    branch: 'hands',
    cost: 8,
    requires: 'hands-1-3',
    effects: [{ kind: 'multiplier', target: 'click', factor: 3 }],
  },
  {
    id: 'hands-1-5',
    name: 'Copper Grip V',
    emoji: '🖐️',
    description: 'Lets practiced fingers move faster without losing the count.',
    branch: 'hands',
    cost: 13,
    requires: 'hands-1-4',
    effects: [{ kind: 'multiplier', target: 'click', factor: 5 }],
  },
  {
    id: 'hands-1-6',
    name: 'Copper Grip VI',
    emoji: '🖐️',
    description: 'Puts the whole hand behind one exceptionally productive gesture.',
    branch: 'hands',
    cost: 21,
    requires: 'hands-1-5',
    effects: [{ kind: 'multiplier', target: 'click', factor: 7 }],
  },
  {
    id: 'hands-1-leaf-1',
    name: 'Brass Knuckle',
    emoji: '🖐️',
    description: 'Gives the working hand one more useful edge.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 2 }],
  },
  {
    id: 'hands-1-leaf-2',
    name: 'Palm Authority',
    emoji: '🖐️',
    description: 'Lets the palm settle an argument with the harvest button.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 3 }],
  },
  {
    id: 'hands-1-leaf-3',
    name: 'Grip of Record',
    emoji: '🖐️',
    description: 'Makes a practiced grip count as official equipment.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 5 }],
  },
  {
    id: 'hands-2-1',
    name: 'Field Rhythm I',
    emoji: '🖐️',
    description: 'Sets a pace the peat cutter can hold without complaint.',
    branch: 'hands',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'fieldwork', factor: 1.25 }],
  },
  {
    id: 'hands-2-2',
    name: 'Field Rhythm II',
    emoji: '🖐️',
    description: 'Makes fieldwork rewards arrive in a more orderly heap.',
    branch: 'hands',
    cost: 6,
    requires: 'hands-2-1',
    effects: [{ kind: 'fieldwork', factor: 1.5 }],
  },
  {
    id: 'hands-2-3',
    name: 'Field Rhythm III',
    emoji: '🖐️',
    description: 'Keeps a wet glove from losing the useful part of the motion.',
    branch: 'hands',
    cost: 10,
    requires: 'hands-2-2',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-2-4',
    name: 'Field Rhythm IV',
    emoji: '🖐️',
    description: 'Turns a repeated cut into a dependable field practice.',
    branch: 'hands',
    cost: 16,
    requires: 'hands-2-3',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-2-5',
    name: 'Field Rhythm V',
    emoji: '🖐️',
    description: 'Lets the cutter work quickly while the bog keeps its dignity.',
    branch: 'hands',
    cost: 26,
    requires: 'hands-2-4',
    effects: [{ kind: 'fieldwork', factor: 5 }],
  },
  {
    id: 'hands-2-6',
    name: 'Field Rhythm VI',
    emoji: '🖐️',
    description: 'Gives every field hand the rhythm of a favourable ruling.',
    branch: 'hands',
    cost: 42,
    requires: 'hands-2-5',
    effects: [{ kind: 'fieldwork', factor: 7 }],
  },
  {
    id: 'hands-2-leaf-1',
    name: 'Peat Measure',
    emoji: '🖐️',
    description: 'Makes the cut worth measuring before the mud closes over it.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-2-6',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-2-leaf-2',
    name: 'Wetland Pace',
    emoji: '🖐️',
    description: 'Sets a pace the wetland can afford to reward.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-2-6',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-3-1',
    name: 'Calibration Palm I',
    emoji: '🖐️',
    description: 'Keeps the calibration hand centred on the useful middle.',
    branch: 'hands',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'fieldwork', factor: 1.25 }],
  },
  {
    id: 'hands-3-2',
    name: 'Calibration Palm II',
    emoji: '🖐️',
    description: 'Makes a close reading pay better than a lucky guess.',
    branch: 'hands',
    cost: 10,
    requires: 'hands-3-1',
    effects: [{ kind: 'fieldwork', factor: 1.5 }],
  },
  {
    id: 'hands-3-3',
    name: 'Calibration Palm III',
    emoji: '🖐️',
    description: 'Turns careful timing into compute and evidence in equal measure.',
    branch: 'hands',
    cost: 15,
    requires: 'hands-3-2',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-3-4',
    name: 'Calibration Palm IV',
    emoji: '🖐️',
    description: 'Lets the palm remember exactly where the target was.',
    branch: 'hands',
    cost: 25,
    requires: 'hands-3-3',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-3-5',
    name: 'Calibration Palm V',
    emoji: '🖐️',
    description: 'Gives each calibration attempt a steadier administrative finish.',
    branch: 'hands',
    cost: 39,
    requires: 'hands-3-4',
    effects: [{ kind: 'fieldwork', factor: 5 }],
  },
  {
    id: 'hands-3-6',
    name: 'Calibration Palm VI',
    emoji: '🖐️',
    description: 'Puts the entire bench behind one immaculate reading.',
    branch: 'hands',
    cost: 63,
    requires: 'hands-3-5',
    effects: [{ kind: 'fieldwork', factor: 7 }],
  },
  {
    id: 'hands-3-leaf-1',
    name: 'True Centre',
    emoji: '🖐️',
    description: 'Finds the centre before the needle has time to wander.',
    branch: 'hands',
    cost: 7,
    requires: 'hands-3-6',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-3-leaf-2',
    name: 'Steady Mark',
    emoji: '🖐️',
    description: 'Leaves a steady mark where the calibration will find it.',
    branch: 'hands',
    cost: 7,
    requires: 'hands-3-6',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-4-1',
    name: 'Click Equity I',
    emoji: '🖐️',
    description: 'Returns a little broth to the hand that earned it.',
    branch: 'hands',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.01 }],
  },
  {
    id: 'hands-4-2',
    name: 'Click Equity II',
    emoji: '🖐️',
    description: 'Makes the harvest button share its proceeds more fairly.',
    branch: 'hands',
    cost: 13,
    requires: 'hands-4-1',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.02 }],
  },
  {
    id: 'hands-4-3',
    name: 'Click Equity III',
    emoji: '🖐️',
    description: 'Turns repeated clicking into a modest evidence practice.',
    branch: 'hands',
    cost: 20,
    requires: 'hands-4-2',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.03 }],
  },
  {
    id: 'hands-4-4',
    name: 'Click Equity IV',
    emoji: '🖐️',
    description: 'Lets every useful press carry a second consequence.',
    branch: 'hands',
    cost: 33,
    requires: 'hands-4-3',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.04 }],
  },
  {
    id: 'hands-4-5',
    name: 'Click Equity V',
    emoji: '🖐️',
    description: 'Keeps the click ledger balanced under heavy use.',
    branch: 'hands',
    cost: 52,
    requires: 'hands-4-4',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.05 }],
  },
  {
    id: 'hands-4-6',
    name: 'Click Equity VI',
    emoji: '🖐️',
    description: 'Gives the working hand its full and properly calculated dividend.',
    branch: 'hands',
    cost: 84,
    requires: 'hands-4-5',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.06 }],
  },
  {
    id: 'hands-4-leaf-1',
    name: 'Broth Rebate',
    emoji: '🖐️',
    description: 'Returns a small rebate before the next click arrives.',
    branch: 'hands',
    cost: 9,
    requires: 'hands-4-6',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.03 }],
  },
  {
    id: 'hands-4-leaf-2',
    name: 'Evidence Share',
    emoji: '🖐️',
    description: 'Sets aside a fair share for the evidence desk.',
    branch: 'hands',
    cost: 9,
    requires: 'hands-4-6',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.05 }],
  },
  {
    id: 'hands-capstone-1',
    name: 'Handwork Charter',
    emoji: '🖐️',
    description: 'Recognises the hand as the first machine in the marsh.',
    branch: 'hands',
    cost: 650,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'multiplier', target: 'click', factor: 7 }],
  },
  {
    id: 'hands-capstone-2',
    name: 'Field Hand Writ',
    emoji: '🖐️',
    description: 'Makes every careful cut admissible as productive fieldwork.',
    branch: 'hands',
    cost: 725,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'fieldwork', factor: 1.8 }],
  },
  {
    id: 'hands-capstone-3',
    name: 'Palm Dividend',
    emoji: '🖐️',
    description: 'Settles the click ledger in favour of the person doing the clicking.',
    branch: 'hands',
    cost: 800,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'clickBrothFraction', fraction: 0.10 }],
  },
  {
    id: 'engines-1-1',
    name: 'Broth Machinery I',
    emoji: '⚙️',
    description: 'Keeps the broth line turning after the first kettle settles.',
    branch: 'engines',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 1.25 }],
  },
  {
    id: 'engines-1-2',
    name: 'Broth Machinery II',
    emoji: '⚙️',
    description: 'Makes the harvester answer more cleanly to its own demand.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-1',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 1.5 }],
  },
  {
    id: 'engines-1-3',
    name: 'Broth Machinery III',
    emoji: '⚙️',
    description: 'Puts a measured increase behind every warm production cycle.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-1-2',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'engines-1-4',
    name: 'Broth Machinery IV',
    emoji: '⚙️',
    description: 'Lets the broth machinery carry a heavier docket.',
    branch: 'engines',
    cost: 8,
    requires: 'engines-1-3',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 3 }],
  },
  {
    id: 'engines-1-5',
    name: 'Broth Machinery V',
    emoji: '⚙️',
    description: 'Turns a serviceable line into the bogs preferred supplier.',
    branch: 'engines',
    cost: 13,
    requires: 'engines-1-4',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 5 }],
  },
  {
    id: 'engines-1-6',
    name: 'Broth Machinery VI',
    emoji: '⚙️',
    description: 'Gives the whole broth floor a formidable mechanical advantage.',
    branch: 'engines',
    cost: 21,
    requires: 'engines-1-5',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 7 }],
  },
  {
    id: 'engines-1-leaf-1',
    name: 'Kettle Allowance',
    emoji: '⚙️',
    description: 'Grants the kettle room for one more useful turn.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'engines-1-leaf-2',
    name: 'Harvester Warrant',
    emoji: '⚙️',
    description: 'Authorises the harvester to exceed its old brief.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 3 }],
  },
  {
    id: 'engines-1-leaf-3',
    name: 'Spare Bearing',
    emoji: '⚙️',
    description: 'Keeps the broth machinery turning through a long inspection.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 5 }],
  },
  {
    id: 'engines-2-1',
    name: 'Cooling Estate I',
    emoji: '⚙️',
    description: 'Gives the cooling line a little more room to breathe.',
    branch: 'engines',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'cooling', factor: 1.05 }],
  },
  {
    id: 'engines-2-2',
    name: 'Cooling Estate II',
    emoji: '⚙️',
    description: 'Keeps the chillers ahead of a modest production dispute.',
    branch: 'engines',
    cost: 6,
    requires: 'engines-2-1',
    effects: [{ kind: 'cooling', factor: 1.1 }],
  },
  {
    id: 'engines-2-3',
    name: 'Cooling Estate III',
    emoji: '⚙️',
    description: 'Turns spare coolant into a quiet thermal advantage.',
    branch: 'engines',
    cost: 10,
    requires: 'engines-2-2',
    effects: [{ kind: 'cooling', factor: 1.2 }],
  },
  {
    id: 'engines-2-4',
    name: 'Cooling Estate IV',
    emoji: '⚙️',
    description: 'Lets the cold side of the plant answer without delay.',
    branch: 'engines',
    cost: 16,
    requires: 'engines-2-3',
    effects: [{ kind: 'cooling', factor: 1.3 }],
  },
  {
    id: 'engines-2-5',
    name: 'Cooling Estate V',
    emoji: '⚙️',
    description: 'Makes the cooling estate broad enough for another rack.',
    branch: 'engines',
    cost: 26,
    requires: 'engines-2-4',
    effects: [{ kind: 'cooling', factor: 1.4 }],
  },
  {
    id: 'engines-2-6',
    name: 'Cooling Estate VI',
    emoji: '⚙️',
    description: 'Puts the entire temperature ledger under excellent management.',
    branch: 'engines',
    cost: 42,
    requires: 'engines-2-5',
    effects: [{ kind: 'cooling', factor: 1.5 }],
  },
  {
    id: 'engines-2-leaf-1',
    name: 'Coolant Lease',
    emoji: '⚙️',
    description: 'Leases one more useful degree of calm to the plant.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-2-6',
    effects: [{ kind: 'cooling', factor: 1.2 }],
  },
  {
    id: 'engines-2-leaf-2',
    name: 'Chiller Easement',
    emoji: '⚙️',
    description: 'Gives the chiller an easement through the hottest hour.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-2-6',
    effects: [{ kind: 'cooling', factor: 1.4 }],
  },
  {
    id: 'engines-3-1',
    name: 'Rack Ordinance I',
    emoji: '⚙️',
    description: 'Lowers the cost of a rack without lowering its standards.',
    branch: 'engines',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'costScale', line: 'broth', delta: -0.005 }],
  },
  {
    id: 'engines-3-2',
    name: 'Rack Ordinance II',
    emoji: '⚙️',
    description: 'Makes compute equipment answerable to a more sensible tariff.',
    branch: 'engines',
    cost: 10,
    requires: 'engines-3-1',
    effects: [{ kind: 'costScale', line: 'peat', delta: -0.008 }],
  },
  {
    id: 'engines-3-3',
    name: 'Rack Ordinance III',
    emoji: '⚙️',
    description: 'Puts the kettle line on a cheaper and sturdier footing.',
    branch: 'engines',
    cost: 15,
    requires: 'engines-3-2',
    effects: [{ kind: 'costScale', line: 'sphagnum', delta: -0.01 }],
  },
  {
    id: 'engines-3-4',
    name: 'Rack Ordinance IV',
    emoji: '⚙️',
    description: 'Reduces the filing cost of machinery the bog already needs.',
    branch: 'engines',
    cost: 25,
    requires: 'engines-3-3',
    effects: [{ kind: 'costScale', line: 'methane', delta: -0.012 }],
  },
  {
    id: 'engines-3-5',
    name: 'Rack Ordinance V',
    emoji: '⚙️',
    description: 'Lets the production lines buy their next argument at a discount.',
    branch: 'engines',
    cost: 39,
    requires: 'engines-3-4',
    effects: [{ kind: 'costScale', line: 'briquettes', delta: -0.015 }],
  },
  {
    id: 'engines-3-6',
    name: 'Rack Ordinance VI',
    emoji: '⚙️',
    description: 'Sets a broad cost precedent across the working plant.',
    branch: 'engines',
    cost: 63,
    requires: 'engines-3-5',
    effects: [{ kind: 'costScale', line: 'briquettes', delta: -0.02 }],
  },
  {
    id: 'engines-3-leaf-1',
    name: 'Fair Rack Price',
    emoji: '⚙️',
    description: 'Sets a fair price on the next rack without touching the warranty.',
    branch: 'engines',
    cost: 7,
    requires: 'engines-3-6',
    effects: [{ kind: 'costScale', line: 'compute', delta: -0.01 }],
  },
  {
    id: 'engines-3-leaf-2',
    name: 'Copper Discount',
    emoji: '⚙️',
    description: 'Finds a small discount in the copper accounts.',
    branch: 'engines',
    cost: 7,
    requires: 'engines-3-6',
    effects: [{ kind: 'costScale', line: 'broth', delta: -0.015 }],
  },
  {
    id: 'engines-4-1',
    name: 'Production Spine I',
    emoji: '⚙️',
    description: 'Places the first free machine where the line can use it.',
    branch: 'engines',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'freeBuildings', buildingId: 'harvester', count: 1 }],
  },
  {
    id: 'engines-4-2',
    name: 'Production Spine II',
    emoji: '⚙️',
    description: 'Adds an unbilled hand to the peat-side operation.',
    branch: 'engines',
    cost: 13,
    requires: 'engines-4-1',
    effects: [{ kind: 'freeBuildings', buildingId: 'peat-cutter', count: 2 }],
  },
  {
    id: 'engines-4-3',
    name: 'Production Spine III',
    emoji: '⚙️',
    description: 'Gives the cooling floor one quiet unit of assistance.',
    branch: 'engines',
    cost: 20,
    requires: 'engines-4-2',
    effects: [{ kind: 'freeBuildings', buildingId: 'chiller', count: 3 }],
  },
  {
    id: 'engines-4-4',
    name: 'Production Spine IV',
    emoji: '⚙️',
    description: 'Sets a complimentary kettle beside the paid machinery.',
    branch: 'engines',
    cost: 33,
    requires: 'engines-4-3',
    effects: [{ kind: 'freeBuildings', buildingId: 'kettle', count: 4 }],
  },
  {
    id: 'engines-4-5',
    name: 'Production Spine V',
    emoji: '⚙️',
    description: 'Puts another still on the books without charging the books.',
    branch: 'engines',
    cost: 52,
    requires: 'engines-4-4',
    effects: [{ kind: 'freeBuildings', buildingId: 'copper-still', count: 5 }],
  },
  {
    id: 'engines-4-6',
    name: 'Production Spine VI',
    emoji: '⚙️',
    description: 'Hands the supercomputer a final rack the ledger cannot invoice.',
    branch: 'engines',
    cost: 84,
    requires: 'engines-4-5',
    effects: [{ kind: 'freeBuildings', buildingId: 'bog-supercomputer', count: 6 }],
  },
  {
    id: 'engines-4-leaf-1',
    name: 'Courtesy Harvester',
    emoji: '⚙️',
    description: 'Places one courtesy harvester beside the first line.',
    branch: 'engines',
    cost: 9,
    requires: 'engines-4-6',
    effects: [{ kind: 'freeBuildings', buildingId: 'harvester', count: 2 }],
  },
  {
    id: 'engines-4-leaf-2',
    name: 'Unbilled Rack',
    emoji: '⚙️',
    description: 'Leaves an unbilled rack humming after the purchase order closes.',
    branch: 'engines',
    cost: 9,
    requires: 'engines-4-6',
    effects: [{ kind: 'freeBuildings', buildingId: 'rack', count: 2 }],
  },
  {
    id: 'engines-capstone-1',
    name: 'Mechanical Settlement',
    emoji: '⚙️',
    description: 'Settles the plant accounts in favour of useful motion.',
    branch: 'engines',
    cost: 650,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'multiplier', target: 'all', factor: 1.5 }],
  },
  {
    id: 'engines-capstone-2',
    name: 'Cool Room Precedent',
    emoji: '⚙️',
    description: 'Makes a cool room the default condition for serious production.',
    branch: 'engines',
    cost: 725,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'cooling', factor: 1.8 }],
  },
  {
    id: 'engines-capstone-3',
    name: 'Machinery Without Invoice',
    emoji: '⚙️',
    description: 'Puts the final machine on the floor without a final bill.',
    branch: 'engines',
    cost: 800,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'freeBuildings', buildingId: 'rack', count: 8 }],
  },
  {
    id: 'lamps-1-1',
    name: 'Midnight Office I',
    emoji: '🕯️',
    description: 'Keeps the midnight office open by one more careful percentage.',
    branch: 'lamps',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'offlineRate', add: 0.01 }],
  },
  {
    id: 'lamps-1-2',
    name: 'Midnight Office II',
    emoji: '🕯️',
    description: 'Lets the last clerk finish a page before sleep.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-1',
    effects: [{ kind: 'offlineRate', add: 0.02 }],
  },
  {
    id: 'lamps-1-3',
    name: 'Midnight Office III',
    emoji: '🕯️',
    description: 'Turns a dark desk into a modest production line.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-1-2',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'lamps-1-4',
    name: 'Midnight Office IV',
    emoji: '🕯️',
    description: 'Makes the hour after closing count for something.',
    branch: 'lamps',
    cost: 8,
    requires: 'lamps-1-3',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'lamps-1-5',
    name: 'Midnight Office V',
    emoji: '🕯️',
    description: 'Keeps a patient lamp over every unattended figure.',
    branch: 'lamps',
    cost: 13,
    requires: 'lamps-1-4',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'lamps-1-6',
    name: 'Midnight Office VI',
    emoji: '🕯️',
    description: 'Gives the night office a rate worthy of its paperwork.',
    branch: 'lamps',
    cost: 21,
    requires: 'lamps-1-5',
    effects: [{ kind: 'offlineRate', add: 0.06 }],
  },
  {
    id: 'lamps-1-leaf-1',
    name: 'Night Margin',
    emoji: '🕯️',
    description: 'Leaves a little production in the margin after dark.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'lamps-1-leaf-2',
    name: 'Moonlit Addendum',
    emoji: '🕯️',
    description: 'Adds one moonlit paragraph to the rate sheet.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'lamps-1-leaf-3',
    name: 'Third Watch',
    emoji: '🕯️',
    description: 'Leaves a lamp burning for the clerk who comes after midnight.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'lamps-2-1',
    name: 'Moon Ledger I',
    emoji: '🕯️',
    description: 'Keeps the moon ledger open through a longer absence.',
    branch: 'lamps',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'offlineCap', addSeconds: 1800 }],
  },
  {
    id: 'lamps-2-2',
    name: 'Moon Ledger II',
    emoji: '🕯️',
    description: 'Adds another interval to the record of unattended work.',
    branch: 'lamps',
    cost: 6,
    requires: 'lamps-2-1',
    effects: [{ kind: 'offlineCap', addSeconds: 3600 }],
  },
  {
    id: 'lamps-2-3',
    name: 'Moon Ledger III',
    emoji: '🕯️',
    description: 'Makes the night clerk willing to wait for the next return.',
    branch: 'lamps',
    cost: 10,
    requires: 'lamps-2-2',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'lamps-2-4',
    name: 'Moon Ledger IV',
    emoji: '🕯️',
    description: 'Stretches the ledger past the ordinary eight-hour courtesy.',
    branch: 'lamps',
    cost: 16,
    requires: 'lamps-2-3',
    effects: [{ kind: 'offlineCap', addSeconds: 10800 }],
  },
  {
    id: 'lamps-2-5',
    name: 'Moon Ledger V',
    emoji: '🕯️',
    description: 'Gives a long absence enough room to remain productive.',
    branch: 'lamps',
    cost: 26,
    requires: 'lamps-2-4',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'lamps-2-6',
    name: 'Moon Ledger VI',
    emoji: '🕯️',
    description: 'Lets the moon ledger cover an entire respectable disappearance.',
    branch: 'lamps',
    cost: 42,
    requires: 'lamps-2-5',
    effects: [{ kind: 'offlineCap', addSeconds: 21600 }],
  },
  {
    id: 'lamps-2-leaf-1',
    name: 'Moon Extension',
    emoji: '🕯️',
    description: 'Extends the moon ledger without disturbing its columns.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-2-6',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'lamps-2-leaf-2',
    name: 'Night Interval',
    emoji: '🕯️',
    description: 'Keeps one more interval available to the absent keeper.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-2-6',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'lamps-3-1',
    name: 'Long Watch I',
    emoji: '🕯️',
    description: 'Makes unattended production return with a little more weight.',
    branch: 'lamps',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'offlineMultiplier', factor: 1.1 }],
  },
  {
    id: 'lamps-3-2',
    name: 'Long Watch II',
    emoji: '🕯️',
    description: 'Keeps the watchful part of the bog from being wasted.',
    branch: 'lamps',
    cost: 10,
    requires: 'lamps-3-1',
    effects: [{ kind: 'offlineMultiplier', factor: 1.2 }],
  },
  {
    id: 'lamps-3-3',
    name: 'Long Watch III',
    emoji: '🕯️',
    description: 'Turns a long absence into a more generous report.',
    branch: 'lamps',
    cost: 15,
    requires: 'lamps-3-2',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'lamps-3-4',
    name: 'Long Watch IV',
    emoji: '🕯️',
    description: 'Lets the night shift retain its better work.',
    branch: 'lamps',
    cost: 25,
    requires: 'lamps-3-3',
    effects: [{ kind: 'offlineMultiplier', factor: 1.4 }],
  },
  {
    id: 'lamps-3-5',
    name: 'Long Watch V',
    emoji: '🕯️',
    description: 'Gives the watch a yield the Magistrate can understand.',
    branch: 'lamps',
    cost: 39,
    requires: 'lamps-3-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'lamps-3-6',
    name: 'Long Watch VI',
    emoji: '🕯️',
    description: 'Returns the full dignity of a properly staffed night.',
    branch: 'lamps',
    cost: 63,
    requires: 'lamps-3-5',
    effects: [{ kind: 'offlineMultiplier', factor: 1.6 }],
  },
  {
    id: 'lamps-3-leaf-1',
    name: 'Watchmans Share',
    emoji: '🕯️',
    description: 'Returns the watchman a fairer share of the quiet yield.',
    branch: 'lamps',
    cost: 7,
    requires: 'lamps-3-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'lamps-3-leaf-2',
    name: 'Darkroom Yield',
    emoji: '🕯️',
    description: 'Makes the darkroom hand back its most useful figures.',
    branch: 'lamps',
    cost: 7,
    requires: 'lamps-3-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'lamps-4-1',
    name: 'Closed Hours I',
    emoji: '🕯️',
    description: 'Keeps closed hours from becoming empty hours.',
    branch: 'lamps',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'offlineRate', add: 0.015 }],
  },
  {
    id: 'lamps-4-2',
    name: 'Closed Hours II',
    emoji: '🕯️',
    description: 'Puts a modest rate behind every locked door.',
    branch: 'lamps',
    cost: 13,
    requires: 'lamps-4-1',
    effects: [{ kind: 'offlineRate', add: 0.025 }],
  },
  {
    id: 'lamps-4-3',
    name: 'Closed Hours III',
    emoji: '🕯️',
    description: 'Makes absence a recognised condition of production.',
    branch: 'lamps',
    cost: 20,
    requires: 'lamps-4-2',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'lamps-4-4',
    name: 'Closed Hours IV',
    emoji: '🕯️',
    description: 'Lets the lamps keep their promise after the keys turn.',
    branch: 'lamps',
    cost: 33,
    requires: 'lamps-4-3',
    effects: [{ kind: 'offlineRate', add: 0.045 }],
  },
  {
    id: 'lamps-4-5',
    name: 'Closed Hours V',
    emoji: '🕯️',
    description: 'Gives the quiet shift a longer and steadier reach.',
    branch: 'lamps',
    cost: 52,
    requires: 'lamps-4-4',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'lamps-4-6',
    name: 'Closed Hours VI',
    emoji: '🕯️',
    description: 'Keeps the whole closed court producing beneath its seal.',
    branch: 'lamps',
    cost: 84,
    requires: 'lamps-4-5',
    effects: [{ kind: 'offlineRate', add: 0.065 }],
  },
  {
    id: 'lamps-4-leaf-1',
    name: 'Locked Door Rate',
    emoji: '🕯️',
    description: 'Keeps one locked door on the production ledger.',
    branch: 'lamps',
    cost: 9,
    requires: 'lamps-4-6',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'lamps-4-leaf-2',
    name: 'After Bell',
    emoji: '🕯️',
    description: 'Lets the after-bell work continue without a witness.',
    branch: 'lamps',
    cost: 9,
    requires: 'lamps-4-6',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'lamps-capstone-1',
    name: 'Lamp Parliament',
    emoji: '🕯️',
    description: 'Gives the night lamps a majority over every empty hour.',
    branch: 'lamps',
    cost: 650,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineRate', add: 0.08 }],
  },
  {
    id: 'lamps-capstone-2',
    name: 'Watch Kept',
    emoji: '🕯️',
    description: 'Records that the watch was kept even when nobody looked.',
    branch: 'lamps',
    cost: 725,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineMultiplier', factor: 1.8 }],
  },
  {
    id: 'lamps-capstone-3',
    name: 'Night Without Adjournment',
    emoji: '🕯️',
    description: 'Leaves the office open until the bog decides otherwise.',
    branch: 'lamps',
    cost: 800,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineCap', addSeconds: 43200 }],
  },
  {
    id: 'stills-1-1',
    name: 'Sludge Alchemy I',
    emoji: '⚗️',
    description: 'Teaches the sludge line to ask less of its input.',
    branch: 'stills',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.98 }],
  },
  {
    id: 'stills-1-2',
    name: 'Sludge Alchemy II',
    emoji: '⚗️',
    description: 'Keeps the first conversion from spilling useful broth.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-1',
    effects: [{ kind: 'converterEfficiency', line: 'peat', factor: 0.95 }],
  },
  {
    id: 'stills-1-3',
    name: 'Sludge Alchemy III',
    emoji: '⚗️',
    description: 'Makes a thick residue answer to a thinner instruction.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-1-2',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.90 }],
  },
  {
    id: 'stills-1-4',
    name: 'Sludge Alchemy IV',
    emoji: '⚗️',
    description: 'Turns the still room waste into a more agreeable feed.',
    branch: 'stills',
    cost: 8,
    requires: 'stills-1-3',
    effects: [{ kind: 'converterEfficiency', line: 'methane', factor: 0.85 }],
  },
  {
    id: 'stills-1-5',
    name: 'Sludge Alchemy V',
    emoji: '⚗️',
    description: 'Lets the sludge line run with a careful economy.',
    branch: 'stills',
    cost: 13,
    requires: 'stills-1-4',
    effects: [{ kind: 'converterEfficiency', line: 'compute', factor: 0.80 }],
  },
  {
    id: 'stills-1-6',
    name: 'Sludge Alchemy VI',
    emoji: '⚗️',
    description: 'Gives every dark vat the efficiency of a seasoned clerk.',
    branch: 'stills',
    cost: 21,
    requires: 'stills-1-5',
    effects: [{ kind: 'converterEfficiency', line: 'briquettes', factor: 0.75 }],
  },
  {
    id: 'stills-1-leaf-1',
    name: 'Dark Vat Allowance',
    emoji: '⚗️',
    description: 'Allows the dark vat to keep its best feedstock.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.90 }],
  },
  {
    id: 'stills-1-leaf-2',
    name: 'Residue Economy',
    emoji: '⚗️',
    description: 'Finds economy in residue that used to be swept aside.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.82 }],
  },
  {
    id: 'stills-1-leaf-3',
    name: 'Clear Distillate',
    emoji: '⚗️',
    description: 'Leaves the first retort cleaner than the docket expected.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.88 }],
  },
  {
    id: 'stills-2-1',
    name: 'Refining Bench I',
    emoji: '⚗️',
    description: 'Gives sludge a cleaner path toward the next useful form.',
    branch: 'stills',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'sludge', factor: 1.25 }],
  },
  {
    id: 'stills-2-2',
    name: 'Refining Bench II',
    emoji: '⚗️',
    description: 'Lets briquettes arrive at the bench with fewer complaints.',
    branch: 'stills',
    cost: 6,
    requires: 'stills-2-1',
    effects: [{ kind: 'multiplier', target: 'briquettes', factor: 1.5 }],
  },
  {
    id: 'stills-2-3',
    name: 'Refining Bench III',
    emoji: '⚗️',
    description: 'Makes refined broth answer more promptly to the still.',
    branch: 'stills',
    cost: 10,
    requires: 'stills-2-2',
    effects: [{ kind: 'multiplier', target: 'refinedBroth', factor: 2 }],
  },
  {
    id: 'stills-2-4',
    name: 'Refining Bench IV',
    emoji: '⚗️',
    description: 'Turns sediment into a resource the clerk can pronounce.',
    branch: 'stills',
    cost: 16,
    requires: 'stills-2-3',
    effects: [{ kind: 'multiplier', target: 'sediment', factor: 3 }],
  },
  {
    id: 'stills-2-5',
    name: 'Refining Bench V',
    emoji: '⚗️',
    description: 'Puts essence within reach of an ordinary production day.',
    branch: 'stills',
    cost: 26,
    requires: 'stills-2-4',
    effects: [{ kind: 'multiplier', target: 'essence', factor: 5 }],
  },
  {
    id: 'stills-2-6',
    name: 'Refining Bench VI',
    emoji: '⚗️',
    description: 'Returns the entire chain to the bench polished and ready.',
    branch: 'stills',
    cost: 42,
    requires: 'stills-2-5',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 7 }],
  },
  {
    id: 'stills-2-leaf-1',
    name: 'Clean Retort',
    emoji: '⚗️',
    description: 'Keeps a clean retort between the sludge and the books.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-2-6',
    effects: [{ kind: 'multiplier', target: 'sludge', factor: 3 }],
  },
  {
    id: 'stills-2-leaf-2',
    name: 'Bright Filtrate',
    emoji: '⚗️',
    description: 'Finds a brighter filtrate hiding in the ordinary run.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-2-6',
    effects: [{ kind: 'multiplier', target: 'essence', factor: 5 }],
  },
  {
    id: 'stills-3-1',
    name: 'Sediment Method I',
    emoji: '⚗️',
    description: 'Lets the still line leave something useful behind.',
    branch: 'stills',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.02 }],
  },
  {
    id: 'stills-3-2',
    name: 'Sediment Method II',
    emoji: '⚗️',
    description: 'Turns a settled layer into a documented secondary yield.',
    branch: 'stills',
    cost: 10,
    requires: 'stills-3-1',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.03 }],
  },
  {
    id: 'stills-3-3',
    name: 'Sediment Method III',
    emoji: '⚗️',
    description: 'Makes each refinement worth checking twice.',
    branch: 'stills',
    cost: 15,
    requires: 'stills-3-2',
    effects: [{ kind: 'byproduct', line: 'briquettes', resource: 'sludge', fraction: 0.04 }],
  },
  {
    id: 'stills-3-4',
    name: 'Sediment Method IV',
    emoji: '⚗️',
    description: 'Keeps sediment from being treated as a clerical error.',
    branch: 'stills',
    cost: 25,
    requires: 'stills-3-3',
    effects: [{ kind: 'byproduct', line: 'refinedBroth', resource: 'essence', fraction: 0.05 }],
  },
  {
    id: 'stills-3-5',
    name: 'Sediment Method V',
    emoji: '⚗️',
    description: 'Gives residue a place in the production settlement.',
    branch: 'stills',
    cost: 39,
    requires: 'stills-3-4',
    effects: [{ kind: 'byproduct', line: 'sediment', resource: 'refinedBroth', fraction: 0.06 }],
  },
  {
    id: 'stills-3-6',
    name: 'Sediment Method VI',
    emoji: '⚗️',
    description: 'Lets every still discharge a useful footnote to the run.',
    branch: 'stills',
    cost: 63,
    requires: 'stills-3-5',
    effects: [{ kind: 'byproduct', line: 'essence', resource: 'sludge', fraction: 0.08 }],
  },
  {
    id: 'stills-3-leaf-1',
    name: 'Settled Yield',
    emoji: '⚗️',
    description: 'Adds a settled yield to the line that made it.',
    branch: 'stills',
    cost: 7,
    requires: 'stills-3-6',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.05 }],
  },
  {
    id: 'stills-3-leaf-2',
    name: 'Second Pour',
    emoji: '⚗️',
    description: 'Keeps a second pour from going quietly to waste.',
    branch: 'stills',
    cost: 7,
    requires: 'stills-3-6',
    effects: [{ kind: 'byproduct', line: 'refinedBroth', resource: 'essence', fraction: 0.07 }],
  },
  {
    id: 'stills-4-1',
    name: 'Essence Practice I',
    emoji: '⚗️',
    description: 'Keeps the essence line from spending more than its recipe.',
    branch: 'stills',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'converterEfficiency', line: 'refinedBroth', factor: 0.97 }],
  },
  {
    id: 'stills-4-2',
    name: 'Essence Practice II',
    emoji: '⚗️',
    description: 'Makes refined broth a calmer input to the final still.',
    branch: 'stills',
    cost: 13,
    requires: 'stills-4-1',
    effects: [{ kind: 'converterEfficiency', line: 'sediment', factor: 0.94 }],
  },
  {
    id: 'stills-4-3',
    name: 'Essence Practice III',
    emoji: '⚗️',
    description: 'Lets sediment cross the bench with less resistance.',
    branch: 'stills',
    cost: 20,
    requires: 'stills-4-2',
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.90 }],
  },
  {
    id: 'stills-4-4',
    name: 'Essence Practice IV',
    emoji: '⚗️',
    description: 'Turns a difficult conversion into a repeatable practice.',
    branch: 'stills',
    cost: 33,
    requires: 'stills-4-3',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.86 }],
  },
  {
    id: 'stills-4-5',
    name: 'Essence Practice V',
    emoji: '⚗️',
    description: 'Gives the essence room to accumulate without fuss.',
    branch: 'stills',
    cost: 52,
    requires: 'stills-4-4',
    effects: [{ kind: 'converterEfficiency', line: 'peat', factor: 0.82 }],
  },
  {
    id: 'stills-4-6',
    name: 'Essence Practice VI',
    emoji: '⚗️',
    description: 'Puts the still room at the height of its own method.',
    branch: 'stills',
    cost: 84,
    requires: 'stills-4-5',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.78 }],
  },
  {
    id: 'stills-4-leaf-1',
    name: 'Final Retort',
    emoji: '⚗️',
    description: 'Keeps the final retort within its written allowance.',
    branch: 'stills',
    cost: 9,
    requires: 'stills-4-6',
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.82 }],
  },
  {
    id: 'stills-4-leaf-2',
    name: 'Stillroom Discipline',
    emoji: '⚗️',
    description: 'Makes discipline the strongest ingredient in the room.',
    branch: 'stills',
    cost: 9,
    requires: 'stills-4-6',
    effects: [{ kind: 'converterEfficiency', line: 'refinedBroth', factor: 0.80 }],
  },
  {
    id: 'stills-capstone-1',
    name: 'Grand Retort',
    emoji: '⚗️',
    description: 'Gives the still room one final and unusually patient hearing.',
    branch: 'stills',
    cost: 650,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'essence', factor: 7 }],
  },
  {
    id: 'stills-capstone-2',
    name: 'Residue Concord',
    emoji: '⚗️',
    description: 'Settles every useful byproduct before it reaches the drain.',
    branch: 'stills',
    cost: 725,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.12 }],
  },
  {
    id: 'stills-capstone-3',
    name: 'Master of Stills',
    emoji: '⚗️',
    description: 'Puts the whole conversion chain under one steady hand.',
    branch: 'stills',
    cost: 800,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.70 }],
  },
  {
    id: 'keepers-1-1',
    name: 'Pierre\'s Furrow I',
    emoji: '🔮',
    description: 'Keeps Pierre’s first furrow attached to every claimed quest.',
    branch: 'keepers',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.01, cap: 1.1 }],
  },
  {
    id: 'keepers-1-2',
    name: 'Pierre\'s Furrow II',
    emoji: '🔮',
    description: 'Makes Pierre’s careful line of work count twice in the ledger.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-1',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.015, cap: 1.15 }],
  },
  {
    id: 'keepers-1-3',
    name: 'Pierre\'s Furrow III',
    emoji: '🔮',
    description: 'Lets an old furrow answer a new settlement question.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-1-2',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.02, cap: 1.2 }],
  },
  {
    id: 'keepers-1-4',
    name: 'Pierre\'s Furrow IV',
    emoji: '🔮',
    description: 'Turns Pierre’s patience into a measurable production advantage.',
    branch: 'keepers',
    cost: 8,
    requires: 'keepers-1-3',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.025, cap: 1.25 }],
  },
  {
    id: 'keepers-1-5',
    name: 'Pierre\'s Furrow V',
    emoji: '🔮',
    description: 'Gives the furrow enough reach to cross another wet season.',
    branch: 'keepers',
    cost: 13,
    requires: 'keepers-1-4',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.03, cap: 1.3 }],
  },
  {
    id: 'keepers-1-6',
    name: 'Pierre\'s Furrow VI',
    emoji: '🔮',
    description: 'Leaves Pierre’s work standing at the edge of the whole docket.',
    branch: 'keepers',
    cost: 21,
    requires: 'keepers-1-5',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.035, cap: 1.4 }],
  },
  {
    id: 'keepers-1-leaf-1',
    name: 'Pierre’s Spare Furrow',
    emoji: '🔮',
    description: 'Keeps one spare furrow ready for the next quest.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'broth', perUnit: 0.03, cap: 1.2 }],
  },
  {
    id: 'keepers-1-leaf-2',
    name: 'Pierre’s Wet Acre',
    emoji: '🔮',
    description: 'Lets a wet acre pay its debt to the quest book.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'peat', perUnit: 0.04, cap: 1.3 }],
  },
  {
    id: 'keepers-1-leaf-3',
    name: 'LLP Exhibit',
    emoji: '🔮',
    description: 'Places one useful filing beside Pierre’s oldest furrow.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'evidence', perUnit: 0.03, cap: 1.2 }],
  },
  {
    id: 'keepers-2-1',
    name: 'Shrome\'s Thread I',
    emoji: '🔮',
    description: 'Keeps Shrome’s thread running through every finished achievement.',
    branch: 'keepers',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.005, cap: 1.05 }],
  },
  {
    id: 'keepers-2-2',
    name: 'Shrome\'s Thread II',
    emoji: '🔮',
    description: 'Makes a completed mark useful beyond the day it was earned.',
    branch: 'keepers',
    cost: 6,
    requires: 'keepers-2-1',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.008, cap: 1.08 }],
  },
  {
    id: 'keepers-2-3',
    name: 'Shrome\'s Thread III',
    emoji: '🔮',
    description: 'Lets the thread tie one small victory to the next.',
    branch: 'keepers',
    cost: 10,
    requires: 'keepers-2-2',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.01, cap: 1.12 }],
  },
  {
    id: 'keepers-2-4',
    name: 'Shrome\'s Thread IV',
    emoji: '🔮',
    description: 'Turns Shrome’s careful stitching into a broader reward.',
    branch: 'keepers',
    cost: 16,
    requires: 'keepers-2-3',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.012, cap: 1.16 }],
  },
  {
    id: 'keepers-2-5',
    name: 'Shrome\'s Thread V',
    emoji: '🔮',
    description: 'Gives the achievement ledger a thread it cannot misplace.',
    branch: 'keepers',
    cost: 26,
    requires: 'keepers-2-4',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.015, cap: 1.2 }],
  },
  {
    id: 'keepers-2-6',
    name: 'Shrome\'s Thread VI',
    emoji: '🔮',
    description: 'Leaves Shrome’s work holding the entire record together.',
    branch: 'keepers',
    cost: 42,
    requires: 'keepers-2-5',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.02, cap: 1.3 }],
  },
  {
    id: 'keepers-2-leaf-1',
    name: 'Shrome’s Knot',
    emoji: '🔮',
    description: 'Ties one more finished achievement into the working record.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-2-6',
    effects: [{ kind: 'perAchievement', target: 'compute', perUnit: 0.015, cap: 1.2 }],
  },
  {
    id: 'keepers-2-leaf-2',
    name: 'Threaded Medal',
    emoji: '🔮',
    description: 'Keeps a medal useful after the applause has stopped.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-2-6',
    effects: [{ kind: 'perAchievement', target: 'evidence', perUnit: 0.02, cap: 1.3 }],
  },
  {
    id: 'keepers-3-1',
    name: 'Samkals\'s Shelf I',
    emoji: '🔮',
    description: 'Keeps Samkals’s shelf moving at the speed of a settled question.',
    branch: 'keepers',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'researchSpeed', factor: 1.05 }],
  },
  {
    id: 'keepers-3-2',
    name: 'Samkals\'s Shelf II',
    emoji: '🔮',
    description: 'Puts one more reference within the researchers’ reach.',
    branch: 'keepers',
    cost: 10,
    requires: 'keepers-3-1',
    effects: [{ kind: 'researchSpeed', factor: 1.1 }],
  },
  {
    id: 'keepers-3-3',
    name: 'Samkals\'s Shelf III',
    emoji: '🔮',
    description: 'Lets the shelf carry a deeper stack of unfinished work.',
    branch: 'keepers',
    cost: 15,
    requires: 'keepers-3-2',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'keepers-3-4',
    name: 'Samkals\'s Shelf IV',
    emoji: '🔮',
    description: 'Turns Samkals’s filing discipline into research time saved.',
    branch: 'keepers',
    cost: 25,
    requires: 'keepers-3-3',
    effects: [{ kind: 'researchSpeed', factor: 1.3 }],
  },
  {
    id: 'keepers-3-5',
    name: 'Samkals\'s Shelf V',
    emoji: '🔮',
    description: 'Gives every useful volume a clearer place in the queue.',
    branch: 'keepers',
    cost: 39,
    requires: 'keepers-3-4',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'keepers-3-6',
    name: 'Samkals\'s Shelf VI',
    emoji: '🔮',
    description: 'Leaves the whole research room indexed under Samkals’s eye.',
    branch: 'keepers',
    cost: 63,
    requires: 'keepers-3-5',
    effects: [{ kind: 'researchSpeed', factor: 1.5 }],
  },
  {
    id: 'keepers-3-leaf-1',
    name: 'Samkals’s Bookmark',
    emoji: '🔮',
    description: 'Marks the page where the next useful answer begins.',
    branch: 'keepers',
    cost: 7,
    requires: 'keepers-3-6',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'keepers-3-leaf-2',
    name: 'Shelf Precedent',
    emoji: '🔮',
    description: 'Makes a well-kept shelf a precedent for speed.',
    branch: 'keepers',
    cost: 7,
    requires: 'keepers-3-6',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'keepers-4-1',
    name: 'McFly\'s Filing I',
    emoji: '🔮',
    description: 'Keeps McFly and Chronicler LLP’s filing on the correct side of history.',
    branch: 'keepers',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'starting', resource: 'broth', amount: 100 }],
  },
  {
    id: 'keepers-4-2',
    name: 'McFly\'s Filing II',
    emoji: '🔮',
    description: 'Gives the LLP one more broth reserve before the next drainage.',
    branch: 'keepers',
    cost: 13,
    requires: 'keepers-4-1',
    effects: [{ kind: 'starting', resource: 'peat', amount: 250 }],
  },
  {
    id: 'keepers-4-3',
    name: 'McFly\'s Filing III',
    emoji: '🔮',
    description: 'Turns a Sector 4 filing into a modest starting advantage.',
    branch: 'keepers',
    cost: 20,
    requires: 'keepers-4-2',
    effects: [{ kind: 'starting', resource: 'compute', amount: 500 }],
  },
  {
    id: 'keepers-4-4',
    name: 'McFly\'s Filing IV',
    emoji: '🔮',
    description: 'Lets the Magistrate find the LLP’s useful clause immediately.',
    branch: 'keepers',
    cost: 33,
    requires: 'keepers-4-3',
    effects: [{ kind: 'starting', resource: 'evidence', amount: 1000 }],
  },
  {
    id: 'keepers-4-5',
    name: 'McFly\'s Filing V',
    emoji: '🔮',
    description: 'Makes every return begin with the paperwork already warm.',
    branch: 'keepers',
    cost: 52,
    requires: 'keepers-4-4',
    effects: [{ kind: 'coreGain', factor: 1.3 }],
  },
  {
    id: 'keepers-4-6',
    name: 'McFly\'s Filing VI',
    emoji: '🔮',
    description: 'Leaves McFly and Chronicler LLP’s signature beneath the whole settlement.',
    branch: 'keepers',
    cost: 84,
    requires: 'keepers-4-5',
    effects: [{ kind: 'coreGain', factor: 1.4 }],
  },
  {
    id: 'keepers-4-leaf-1',
    name: 'LLP Retainer',
    emoji: '🔮',
    description: 'Keeps a retainer of broth ready for the next run.',
    branch: 'keepers',
    cost: 9,
    requires: 'keepers-4-6',
    effects: [{ kind: 'starting', resource: 'broth', amount: 500 }],
  },
  {
    id: 'keepers-4-leaf-2',
    name: 'Sector Four Clause',
    emoji: '🔮',
    description: 'Brings one useful Sector 4 clause into the new run.',
    branch: 'keepers',
    cost: 9,
    requires: 'keepers-4-6',
    effects: [{ kind: 'starting', resource: 'compute', amount: 1000 }],
  },
  {
    id: 'keepers-capstone-1',
    name: 'Pierre’s Final Furrow',
    emoji: '🔮',
    description: 'Lets Pierre’s furrow run beneath every quest still to be claimed.',
    branch: 'keepers',
    cost: 650,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.05, cap: 1.5 }],
  },
  {
    id: 'keepers-capstone-2',
    name: 'Shrome’s Binding Thread',
    emoji: '🔮',
    description: 'Binds every achievement into one unusually durable reward.',
    branch: 'keepers',
    cost: 725,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.03, cap: 1.4 }],
  },
  {
    id: 'keepers-capstone-3',
    name: 'McFly’s Counterseal',
    emoji: '🔮',
    description: 'Sets the LLP counterseal beside the Magistrate’s original wax.',
    branch: 'keepers',
    cost: 800,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'coreGain', factor: 1.6 }],
  },
];
