import type { CharterNodeDef } from './charter';

/** Authored terms for the eight expanded Drainage Charter wings. */
export const WING_NODES: CharterNodeDef[] = [
  {
    id: 'roots-1-1',
    name: 'Water Table I',
    emoji: '🌿',
    description: 'Water Table I holds the low ground against another dry season.',
    branch: 'roots',
    cost: 2,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 1.25 }],
  },
  {
    id: 'roots-1-2',
    name: 'Water Table II',
    emoji: '🌿',
    description: 'Water Table II marks the channels where clean peat can still be lifted.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-1',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 1.5 }],
  },
  {
    id: 'roots-1-3',
    name: 'Water Table III',
    emoji: '🌿',
    description: 'Water Table III keeps the harvesters from arguing with the waterline.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-1-2',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 2 }],
  },
  {
    id: 'roots-1-4',
    name: 'Water Table IV',
    emoji: '🌿',
    description: 'Water Table IV puts a firm boundary around the wettest beds.',
    branch: 'roots',
    cost: 8,
    requires: 'roots-1-3',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 3 }],
  },
  {
    id: 'roots-1-5',
    name: 'Water Table V',
    emoji: '🌿',
    description: 'Water Table V turns standing water into a patient reserve.',
    branch: 'roots',
    cost: 13,
    requires: 'roots-1-4',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 5 }],
  },
  {
    id: 'roots-1-6',
    name: 'Water Table VI',
    emoji: '🌿',
    description: 'Water Table VI leaves the whole basin better than the survey found it.',
    branch: 'roots',
    cost: 21,
    requires: 'roots-1-5',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 7 }],
  },
  {
    id: 'roots-1-leaf-1',
    name: 'Sluice Witness',
    emoji: '🌿',
    description: 'Sluice Witness keeps the sluice book honest when the rain arrives.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 2 }],
  },
  {
    id: 'roots-1-leaf-2',
    name: 'Tussock Key',
    emoji: '🌿',
    description: 'Tussock Key opens a dry path through ground that prefers to close.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 3 }],
  },
  {
    id: 'roots-1-leaf-3',
    name: 'Fen Boundary',
    emoji: '🌿',
    description: 'Fen Boundary settles the boundary dispute without moving a single marker.',
    branch: 'roots',
    cost: 3,
    requires: 'roots-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'roots-2-1',
    name: 'Tussock Memory I',
    emoji: '🌿',
    description: 'Tussock Memory I keeps a pressed copy of every useful green surface.',
    branch: 'roots',
    cost: 4,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 1.25 }],
  },
  {
    id: 'roots-2-2',
    name: 'Tussock Memory II',
    emoji: '🌿',
    description: 'Tussock Memory II teaches the cutters which moss will spring back overnight.',
    branch: 'roots',
    cost: 6,
    requires: 'roots-2-1',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 1.5 }],
  },
  {
    id: 'roots-2-3',
    name: 'Tussock Memory III',
    emoji: '🌿',
    description: 'Tussock Memory III stores the bogs older answers under fresh growth.',
    branch: 'roots',
    cost: 10,
    requires: 'roots-2-2',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 2 }],
  },
  {
    id: 'roots-2-4',
    name: 'Tussock Memory IV',
    emoji: '🌿',
    description: 'Tussock Memory IV makes soft ground count as a reliable witness.',
    branch: 'roots',
    cost: 16,
    requires: 'roots-2-3',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 3 }],
  },
  {
    id: 'roots-2-5',
    name: 'Tussock Memory V',
    emoji: '🌿',
    description: 'Tussock Memory V lets the harvest borrow strength from last years rain.',
    branch: 'roots',
    cost: 26,
    requires: 'roots-2-4',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 5 }],
  },
  {
    id: 'roots-2-6',
    name: 'Tussock Memory VI',
    emoji: '🌿',
    description: 'Tussock Memory VI returns the whole tussock field to its proper account.',
    branch: 'roots',
    cost: 42,
    requires: 'roots-2-5',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 7 }],
  },
  {
    id: 'roots-2-leaf-1',
    name: 'Moss Witness',
    emoji: '🌿',
    description: 'Moss Witness signs for a harvest the court would otherwise lose.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-2-6',
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 2 }],
  },
  {
    id: 'roots-2-leaf-2',
    name: 'Green Margin',
    emoji: '🌿',
    description: 'Green Margin leaves one careful margin for the next growth cycle.',
    branch: 'roots',
    cost: 5,
    requires: 'roots-2-6',
    effects: [{ kind: 'multiplier', target: 'peat', factor: 3 }],
  },
  {
    id: 'roots-3-1',
    name: 'Waterlogged Archive I',
    emoji: '🌿',
    description: 'Waterlogged Archive I keeps old drainage maps legible beneath the brown water.',
    branch: 'roots',
    cost: 6,
    requires: 'roots-4',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 1.25 }],
  },
  {
    id: 'roots-3-2',
    name: 'Waterlogged Archive II',
    emoji: '🌿',
    description: 'Waterlogged Archive II finds the useful paragraph in a sodden record.',
    branch: 'roots',
    cost: 10,
    requires: 'roots-3-1',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 1.5 }],
  },
  {
    id: 'roots-3-3',
    name: 'Waterlogged Archive III',
    emoji: '🌿',
    description: 'Waterlogged Archive III teaches the docket which scraps of evidence still float.',
    branch: 'roots',
    cost: 15,
    requires: 'roots-3-2',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 2 }],
  },
  {
    id: 'roots-3-4',
    name: 'Waterlogged Archive IV',
    emoji: '🌿',
    description: 'Waterlogged Archive IV makes a wet archive serve a dry calculation.',
    branch: 'roots',
    cost: 25,
    requires: 'roots-3-3',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 3 }],
  },
  {
    id: 'roots-3-5',
    name: 'Waterlogged Archive V',
    emoji: '🌿',
    description: 'Waterlogged Archive V binds the surviving pages into a working ledger.',
    branch: 'roots',
    cost: 39,
    requires: 'roots-3-4',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 5 }],
  },
  {
    id: 'roots-3-6',
    name: 'Waterlogged Archive VI',
    emoji: '🌿',
    description: 'Waterlogged Archive VI gives the bog a memory that no flood can amend.',
    branch: 'roots',
    cost: 63,
    requires: 'roots-3-5',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 7 }],
  },
  {
    id: 'roots-3-leaf-1',
    name: 'Flooded Index',
    emoji: '🌿',
    description: 'Flooded Index puts the submerged records back in alphabetical order.',
    branch: 'roots',
    cost: 7,
    requires: 'roots-3-6',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 2 }],
  },
  {
    id: 'roots-3-leaf-2',
    name: 'Sodden Exhibit',
    emoji: '🌿',
    description: 'Sodden Exhibit admits one damp exhibit and finds it surprisingly useful.',
    branch: 'roots',
    cost: 7,
    requires: 'roots-3-6',
    effects: [{ kind: 'multiplier', target: 'evidence', factor: 3 }],
  },
  {
    id: 'roots-4-1',
    name: 'Peat Inheritance I',
    emoji: '🌿',
    description: 'Peat Inheritance I passes the first good habit from one run to the next.',
    branch: 'roots',
    cost: 8,
    requires: 'roots-4',
    effects: [{ kind: 'startingBroth', amount: 100 }],
  },
  {
    id: 'roots-4-2',
    name: 'Peat Inheritance II',
    emoji: '🌿',
    description: 'Peat Inheritance II leaves the cutters a little broth before the gates open.',
    branch: 'roots',
    cost: 13,
    requires: 'roots-4-1',
    effects: [{ kind: 'startingBroth', amount: 250 }],
  },
  {
    id: 'roots-4-3',
    name: 'Peat Inheritance III',
    emoji: '🌿',
    description: 'Peat Inheritance III teaches a drained bog to begin with something in reserve.',
    branch: 'roots',
    cost: 20,
    requires: 'roots-4-2',
    effects: [{ kind: 'startingBroth', amount: 500 }],
  },
  {
    id: 'roots-4-4',
    name: 'Peat Inheritance IV',
    emoji: '🌿',
    description: 'Peat Inheritance IV keeps the familys useful mistakes out of the new ledger.',
    branch: 'roots',
    cost: 33,
    requires: 'roots-4-3',
    effects: [{ kind: 'startingBroth', amount: 1000 }],
  },
  {
    id: 'roots-4-5',
    name: 'Peat Inheritance V',
    emoji: '🌿',
    description: 'Peat Inheritance V makes every return feel less like starting over.',
    branch: 'roots',
    cost: 52,
    requires: 'roots-4-4',
    effects: [{ kind: 'startingBroth', amount: 2000 }],
  },
  {
    id: 'roots-4-6',
    name: 'Peat Inheritance VI',
    emoji: '🌿',
    description: 'Peat Inheritance VI hands the next run an inheritance the court cannot tax.',
    branch: 'roots',
    cost: 84,
    requires: 'roots-4-5',
    effects: [{ kind: 'startingBroth', amount: 4000 }],
  },
  {
    id: 'roots-4-leaf-1',
    name: 'Inherited Spade',
    emoji: '🌿',
    description: 'Inherited Spade sets a spare spade beside the first empty trench.',
    branch: 'roots',
    cost: 9,
    requires: 'roots-4-6',
    effects: [{ kind: 'startingBroth', amount: 500 }],
  },
  {
    id: 'roots-4-leaf-2',
    name: 'Heirloom Sump',
    emoji: '🌿',
    description: 'Heirloom Sump keeps one useful sump waiting through the reset.',
    branch: 'roots',
    cost: 9,
    requires: 'roots-4-6',
    effects: [{ kind: 'startingBroth', amount: 1000 }],
  },
  {
    id: 'roots-capstone-1',
    name: 'Greenwater Concord',
    emoji: '🌿',
    description: 'Greenwater Concord joins the root records into one settlement the bog will honour.',
    branch: 'roots',
    cost: 650,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'peat', factor: 7 }],
  },
  {
    id: 'roots-capstone-2',
    name: 'Inheritance Writ',
    emoji: '🌿',
    description: 'Inheritance Writ makes old growth admissible in every future proceeding.',
    branch: 'roots',
    cost: 725,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'sphagnum', factor: 7 }],
  },
  {
    id: 'roots-capstone-3',
    name: 'Basin Memory',
    emoji: '🌿',
    description: 'Basin Memory closes the roots ledger with no useful habit left unsigned.',
    branch: 'roots',
    cost: 800,
    requires: 'roots-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'all', factor: 1.5 }],
  },
  {
    id: 'kindling-1-1',
    name: 'Boiler Practice I',
    emoji: '🔥',
    description: 'Boiler Practice I keeps the first flame below the threshold of complaint.',
    branch: 'kindling',
    cost: 2,
    requires: 'kindling-4',
    effects: [{ kind: 'heat', factor: 0.98 }],
  },
  {
    id: 'kindling-1-2',
    name: 'Boiler Practice II',
    emoji: '🔥',
    description: 'Boiler Practice II teaches the boiler to waste less heat on the rafters.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-1',
    effects: [{ kind: 'heat', factor: 0.96 }],
  },
  {
    id: 'kindling-1-3',
    name: 'Boiler Practice III',
    emoji: '🔥',
    description: 'Boiler Practice III makes a warm rack answer to a cooler order.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-1-2',
    effects: [{ kind: 'heat', factor: 0.94 }],
  },
  {
    id: 'kindling-1-4',
    name: 'Boiler Practice IV',
    emoji: '🔥',
    description: 'Boiler Practice IV puts every flare on a schedule the clerk can read.',
    branch: 'kindling',
    cost: 8,
    requires: 'kindling-1-3',
    effects: [{ kind: 'heat', factor: 0.92 }],
  },
  {
    id: 'kindling-1-5',
    name: 'Boiler Practice V',
    emoji: '🔥',
    description: 'Boiler Practice V turns excess heat into a signed procedural error.',
    branch: 'kindling',
    cost: 13,
    requires: 'kindling-1-4',
    effects: [{ kind: 'heat', factor: 0.9 }],
  },
  {
    id: 'kindling-1-6',
    name: 'Boiler Practice VI',
    emoji: '🔥',
    description: 'Boiler Practice VI leaves the whole boiler room running hot but civil.',
    branch: 'kindling',
    cost: 21,
    requires: 'kindling-1-5',
    effects: [{ kind: 'heat', factor: 0.88 }],
  },
  {
    id: 'kindling-1-leaf-1',
    name: 'Quiet Flue',
    emoji: '🔥',
    description: 'Quiet Flue lets one stubborn flue carry its heat without shouting.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.90 }],
  },
  {
    id: 'kindling-1-leaf-2',
    name: 'Boiler Margin',
    emoji: '🔥',
    description: 'Boiler Margin reserves a little room beneath the red line.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.88 }],
  },
  {
    id: 'kindling-1-leaf-3',
    name: 'Ash Ruling',
    emoji: '🔥',
    description: 'Ash Ruling records the ash as evidence rather than waste.',
    branch: 'kindling',
    cost: 3,
    requires: 'kindling-1-6',
    effects: [{ kind: 'heat', factor: 0.92 }],
  },
  {
    id: 'kindling-2-1',
    name: 'Methane Docket I',
    emoji: '🔥',
    description: 'Methane Docket I puts the gas on the record before it wanders off.',
    branch: 'kindling',
    cost: 4,
    requires: 'kindling-4',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 1.25 }],
  },
  {
    id: 'kindling-2-2',
    name: 'Methane Docket II',
    emoji: '🔥',
    description: 'Methane Docket II makes a methane bloom answer the same question twice.',
    branch: 'kindling',
    cost: 6,
    requires: 'kindling-2-1',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 1.5 }],
  },
  {
    id: 'kindling-2-3',
    name: 'Methane Docket III',
    emoji: '🔥',
    description: 'Methane Docket III keeps the rising pressure useful instead of dramatic.',
    branch: 'kindling',
    cost: 10,
    requires: 'kindling-2-2',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 2 }],
  },
  {
    id: 'kindling-2-4',
    name: 'Methane Docket IV',
    emoji: '🔥',
    description: 'Methane Docket IV turns a suspicious hiss into a dependable supply.',
    branch: 'kindling',
    cost: 16,
    requires: 'kindling-2-3',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 3 }],
  },
  {
    id: 'kindling-2-5',
    name: 'Methane Docket V',
    emoji: '🔥',
    description: 'Methane Docket V gives the gas line a witness and a timetable.',
    branch: 'kindling',
    cost: 26,
    requires: 'kindling-2-4',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 5 }],
  },
  {
    id: 'kindling-2-6',
    name: 'Methane Docket VI',
    emoji: '🔥',
    description: 'Methane Docket VI lets the whole methane docket speak at full volume.',
    branch: 'kindling',
    cost: 42,
    requires: 'kindling-2-5',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 7 }],
  },
  {
    id: 'kindling-2-leaf-1',
    name: 'Gas Affidavit',
    emoji: '🔥',
    description: 'Gas Affidavit gets the gas to swear it was present all along.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-2-6',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 3 }],
  },
  {
    id: 'kindling-2-leaf-2',
    name: 'Rising Clause',
    emoji: '🔥',
    description: 'Rising Clause adds a clause for pressure that refuses to wait.',
    branch: 'kindling',
    cost: 5,
    requires: 'kindling-2-6',
    effects: [{ kind: 'multiplier', target: 'methane', factor: 5 }],
  },
  {
    id: 'kindling-3-1',
    name: 'Rack Ember I',
    emoji: '🔥',
    description: 'Rack Ember I keeps one ember where the compute racks can reach it.',
    branch: 'kindling',
    cost: 6,
    requires: 'kindling-4',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 1.25 }],
  },
  {
    id: 'kindling-3-2',
    name: 'Rack Ember II',
    emoji: '🔥',
    description: 'Rack Ember II makes the rack room take a faster but tidier breath.',
    branch: 'kindling',
    cost: 10,
    requires: 'kindling-3-1',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 1.5 }],
  },
  {
    id: 'kindling-3-3',
    name: 'Rack Ember III',
    emoji: '🔥',
    description: 'Rack Ember III turns a stray spark into a useful compute allowance.',
    branch: 'kindling',
    cost: 15,
    requires: 'kindling-3-2',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 2 }],
  },
  {
    id: 'kindling-3-4',
    name: 'Rack Ember IV',
    emoji: '🔥',
    description: 'Rack Ember IV lets every warm shelf carry its share of the verdict.',
    branch: 'kindling',
    cost: 25,
    requires: 'kindling-3-3',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 3 }],
  },
  {
    id: 'kindling-3-5',
    name: 'Rack Ember V',
    emoji: '🔥',
    description: 'Rack Ember V gives the racks enough ember to finish the argument.',
    branch: 'kindling',
    cost: 39,
    requires: 'kindling-3-4',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 5 }],
  },
  {
    id: 'kindling-3-6',
    name: 'Rack Ember VI',
    emoji: '🔥',
    description: 'Rack Ember VI sets the entire compute room alight without burning the docket.',
    branch: 'kindling',
    cost: 63,
    requires: 'kindling-3-5',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 7 }],
  },
  {
    id: 'kindling-3-leaf-1',
    name: 'Rack Spark',
    emoji: '🔥',
    description: 'Rack Spark keeps a small spark under every working shelf.',
    branch: 'kindling',
    cost: 7,
    requires: 'kindling-3-6',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 3 }],
  },
  {
    id: 'kindling-3-leaf-2',
    name: 'Hot Verdict',
    emoji: '🔥',
    description: 'Hot Verdict delivers the ruling before the cooling clerk objects.',
    branch: 'kindling',
    cost: 7,
    requires: 'kindling-3-6',
    effects: [{ kind: 'multiplier', target: 'compute', factor: 5 }],
  },
  {
    id: 'kindling-4-1',
    name: 'Verdict Spark I',
    emoji: '🔥',
    description: 'Verdict Spark I moves the research docket before the first kettle boils.',
    branch: 'kindling',
    cost: 8,
    requires: 'kindling-4',
    effects: [{ kind: 'researchSpeed', factor: 1.05 }],
  },
  {
    id: 'kindling-4-2',
    name: 'Verdict Spark II',
    emoji: '🔥',
    description: 'Verdict Spark II gives the clerks a lamp bright enough for another page.',
    branch: 'kindling',
    cost: 13,
    requires: 'kindling-4-1',
    effects: [{ kind: 'researchSpeed', factor: 1.1 }],
  },
  {
    id: 'kindling-4-3',
    name: 'Verdict Spark III',
    emoji: '🔥',
    description: 'Verdict Spark III makes a second reading feel less like a delay.',
    branch: 'kindling',
    cost: 20,
    requires: 'kindling-4-2',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'kindling-4-4',
    name: 'Verdict Spark IV',
    emoji: '🔥',
    description: 'Verdict Spark IV puts the useful result at the top of the stack.',
    branch: 'kindling',
    cost: 33,
    requires: 'kindling-4-3',
    effects: [{ kind: 'researchSpeed', factor: 1.3 }],
  },
  {
    id: 'kindling-4-5',
    name: 'Verdict Spark V',
    emoji: '🔥',
    description: 'Verdict Spark V turns a long review into a brisk administrative matter.',
    branch: 'kindling',
    cost: 52,
    requires: 'kindling-4-4',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'kindling-4-6',
    name: 'Verdict Spark VI',
    emoji: '🔥',
    description: 'Verdict Spark VI lets the whole research bench reach its conclusion early.',
    branch: 'kindling',
    cost: 84,
    requires: 'kindling-4-5',
    effects: [{ kind: 'researchSpeed', factor: 1.5 }],
  },
  {
    id: 'kindling-4-leaf-1',
    name: 'Prompt Finding',
    emoji: '🔥',
    description: 'Prompt Finding finds the answer in the margin before the hearing begins.',
    branch: 'kindling',
    cost: 9,
    requires: 'kindling-4-6',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'kindling-4-leaf-2',
    name: 'Early Ruling',
    emoji: '🔥',
    description: 'Early Ruling places a useful ruling where the researchers can reach it.',
    branch: 'kindling',
    cost: 9,
    requires: 'kindling-4-6',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'kindling-capstone-1',
    name: 'Boiler Sentence',
    emoji: '🔥',
    description: 'Boiler Sentence makes the heat ledger answer for every careless flame.',
    branch: 'kindling',
    cost: 650,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'heat', factor: 0.80 }],
  },
  {
    id: 'kindling-capstone-2',
    name: 'Methane Verdict',
    emoji: '🔥',
    description: 'Methane Verdict gives the gas a final ruling and a larger room to rise in.',
    branch: 'kindling',
    cost: 725,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'multiplier', target: 'methane', factor: 7 }],
  },
  {
    id: 'kindling-capstone-3',
    name: 'Ember Precedent',
    emoji: '🔥',
    description: 'Ember Precedent sets a bright precedent for every rack that follows.',
    branch: 'kindling',
    cost: 800,
    requires: 'kindling-4-leaf-2',
    requiresAny: ['engines-1-1'],
    effects: [{ kind: 'multiplier', target: 'compute', factor: 7 }],
  },
  {
    id: 'filing-1-1',
    name: 'Night Docket I',
    emoji: '🕯️',
    description: 'Night Docket I keeps the evening docket open past the sensible hour.',
    branch: 'filing',
    cost: 2,
    requires: 'filing-4',
    effects: [{ kind: 'offlineRate', add: 0.01 }],
  },
  {
    id: 'filing-1-2',
    name: 'Night Docket II',
    emoji: '🕯️',
    description: 'Night Docket II lets one more filing cross the desk before dawn.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-1',
    effects: [{ kind: 'offlineRate', add: 0.02 }],
  },
  {
    id: 'filing-1-3',
    name: 'Night Docket III',
    emoji: '🕯️',
    description: 'Night Docket III makes the night clerk less dependent on daylight.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-1-2',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'filing-1-4',
    name: 'Night Docket IV',
    emoji: '🕯️',
    description: 'Night Docket IV turns late work into a standing administrative habit.',
    branch: 'filing',
    cost: 8,
    requires: 'filing-1-3',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'filing-1-5',
    name: 'Night Docket V',
    emoji: '🕯️',
    description: 'Night Docket V keeps every after-hours page moving through the room.',
    branch: 'filing',
    cost: 13,
    requires: 'filing-1-4',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'filing-1-6',
    name: 'Night Docket VI',
    emoji: '🕯️',
    description: 'Night Docket VI gives the dark a full and properly indexed docket.',
    branch: 'filing',
    cost: 21,
    requires: 'filing-1-5',
    effects: [{ kind: 'offlineRate', add: 0.06 }],
  },
  {
    id: 'filing-1-leaf-1',
    name: 'Afterhours Stamp',
    emoji: '🕯️',
    description: 'Afterhours Stamp puts a quiet stamp on work done after closing.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'filing-1-leaf-2',
    name: 'Midnight Seal',
    emoji: '🕯️',
    description: 'Midnight Seal keeps the last seal warm until the morning shift.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'filing-1-leaf-3',
    name: 'Late Filing',
    emoji: '🕯️',
    description: 'Late Filing accepts one more filing without waking the Magistrate.',
    branch: 'filing',
    cost: 3,
    requires: 'filing-1-6',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'filing-2-1',
    name: 'Clerk Circuit I',
    emoji: '🕯️',
    description: 'Clerk Circuit I keeps the clerk moving between lamps without losing the thread.',
    branch: 'filing',
    cost: 4,
    requires: 'filing-4',
    effects: [{ kind: 'offlineRate', add: 0.015 }],
  },
  {
    id: 'filing-2-2',
    name: 'Clerk Circuit II',
    emoji: '🕯️',
    description: 'Clerk Circuit II adds another reliable circuit to the late-night office.',
    branch: 'filing',
    cost: 6,
    requires: 'filing-2-1',
    effects: [{ kind: 'offlineRate', add: 0.025 }],
  },
  {
    id: 'filing-2-3',
    name: 'Clerk Circuit III',
    emoji: '🕯️',
    description: 'Clerk Circuit III makes every dark corridor part of the same ledger.',
    branch: 'filing',
    cost: 10,
    requires: 'filing-2-2',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'filing-2-4',
    name: 'Clerk Circuit IV',
    emoji: '🕯️',
    description: 'Clerk Circuit IV lets a careful clerk carry two dockets at once.',
    branch: 'filing',
    cost: 16,
    requires: 'filing-2-3',
    effects: [{ kind: 'offlineRate', add: 0.045 }],
  },
  {
    id: 'filing-2-5',
    name: 'Clerk Circuit V',
    emoji: '🕯️',
    description: 'Clerk Circuit V puts the whole circuit under a single night order.',
    branch: 'filing',
    cost: 26,
    requires: 'filing-2-4',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'filing-2-6',
    name: 'Clerk Circuit VI',
    emoji: '🕯️',
    description: 'Clerk Circuit VI keeps the filing room working when the bog goes quiet.',
    branch: 'filing',
    cost: 42,
    requires: 'filing-2-5',
    effects: [{ kind: 'offlineRate', add: 0.065 }],
  },
  {
    id: 'filing-2-leaf-1',
    name: 'Second Circuit',
    emoji: '🕯️',
    description: 'Second Circuit adds a second circuit where the first one tired.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-2-6',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'filing-2-leaf-2',
    name: 'Clerk Relay',
    emoji: '🕯️',
    description: 'Clerk Relay passes the ledger to a clerk who was already waiting.',
    branch: 'filing',
    cost: 5,
    requires: 'filing-2-6',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'filing-3-1',
    name: 'Away Record I',
    emoji: '🕯️',
    description: 'Away Record I keeps a clean record of the hours nobody witnessed.',
    branch: 'filing',
    cost: 6,
    requires: 'filing-4',
    effects: [{ kind: 'offlineCap', addSeconds: 1800 }],
  },
  {
    id: 'filing-3-2',
    name: 'Away Record II',
    emoji: '🕯️',
    description: 'Away Record II adds another page to the archive of unattended work.',
    branch: 'filing',
    cost: 10,
    requires: 'filing-3-1',
    effects: [{ kind: 'offlineCap', addSeconds: 3600 }],
  },
  {
    id: 'filing-3-3',
    name: 'Away Record III',
    emoji: '🕯️',
    description: 'Away Record III makes absence count as a modest form of supervision.',
    branch: 'filing',
    cost: 15,
    requires: 'filing-3-2',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'filing-3-4',
    name: 'Away Record IV',
    emoji: '🕯️',
    description: 'Away Record IV lets the ledger remember what happened while doors were shut.',
    branch: 'filing',
    cost: 25,
    requires: 'filing-3-3',
    effects: [{ kind: 'offlineCap', addSeconds: 10800 }],
  },
  {
    id: 'filing-3-5',
    name: 'Away Record V',
    emoji: '🕯️',
    description: 'Away Record V keeps the away record open through a longer silence.',
    branch: 'filing',
    cost: 39,
    requires: 'filing-3-4',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'filing-3-6',
    name: 'Away Record VI',
    emoji: '🕯️',
    description: 'Away Record VI turns unattended hours into a respectable institutional memory.',
    branch: 'filing',
    cost: 63,
    requires: 'filing-3-5',
    effects: [{ kind: 'offlineCap', addSeconds: 21600 }],
  },
  {
    id: 'filing-3-leaf-1',
    name: 'Extended Docket',
    emoji: '🕯️',
    description: 'Extended Docket leaves the docket open for one more useful interval.',
    branch: 'filing',
    cost: 7,
    requires: 'filing-3-6',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'filing-3-leaf-2',
    name: 'Long Adjournment',
    emoji: '🕯️',
    description: 'Long Adjournment makes an adjournment long enough to be worth recording.',
    branch: 'filing',
    cost: 7,
    requires: 'filing-3-6',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'filing-4-1',
    name: 'Lamp Continuance I',
    emoji: '🕯️',
    description: 'Lamp Continuance I keeps the lamps lit without pretending the court is awake.',
    branch: 'filing',
    cost: 8,
    requires: 'filing-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.1 }],
  },
  {
    id: 'filing-4-2',
    name: 'Lamp Continuance II',
    emoji: '🕯️',
    description: 'Lamp Continuance II makes unattended production a little less apologetic.',
    branch: 'filing',
    cost: 13,
    requires: 'filing-4-1',
    effects: [{ kind: 'offlineMultiplier', factor: 1.2 }],
  },
  {
    id: 'filing-4-3',
    name: 'Lamp Continuance III',
    emoji: '🕯️',
    description: 'Lamp Continuance III lets the night office keep more of what it starts.',
    branch: 'filing',
    cost: 20,
    requires: 'filing-4-2',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'filing-4-4',
    name: 'Lamp Continuance IV',
    emoji: '🕯️',
    description: 'Lamp Continuance IV turns a dim continuation into a dependable one.',
    branch: 'filing',
    cost: 33,
    requires: 'filing-4-3',
    effects: [{ kind: 'offlineMultiplier', factor: 1.4 }],
  },
  {
    id: 'filing-4-5',
    name: 'Lamp Continuance V',
    emoji: '🕯️',
    description: 'Lamp Continuance V gives the lamps enough patience for a full absence.',
    branch: 'filing',
    cost: 52,
    requires: 'filing-4-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'filing-4-6',
    name: 'Lamp Continuance VI',
    emoji: '🕯️',
    description: 'Lamp Continuance VI keeps the whole night court bright at its quietest.',
    branch: 'filing',
    cost: 84,
    requires: 'filing-4-5',
    effects: [{ kind: 'offlineMultiplier', factor: 1.6 }],
  },
  {
    id: 'filing-4-leaf-1',
    name: 'Quiet Continuance',
    emoji: '🕯️',
    description: 'Quiet Continuance continues the work quietly and returns a little more of it.',
    branch: 'filing',
    cost: 9,
    requires: 'filing-4-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'filing-4-leaf-2',
    name: 'Closed Court Yield',
    emoji: '🕯️',
    description: 'Closed Court Yield lets the closed court keep its best unfinished business.',
    branch: 'filing',
    cost: 9,
    requires: 'filing-4-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'filing-capstone-1',
    name: 'Nocturne Filing',
    emoji: '🕯️',
    description: 'Nocturne Filing keeps every useful night entry together under one dark cover.',
    branch: 'filing',
    cost: 650,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineRate', add: 0.08 }],
  },
  {
    id: 'filing-capstone-2',
    name: 'Clerk of Last Light',
    emoji: '🕯️',
    description: 'Clerk of Last Light appoints the last lamp to a post it cannot abandon.',
    branch: 'filing',
    cost: 725,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineMultiplier', factor: 1.8 }],
  },
  {
    id: 'filing-capstone-3',
    name: 'Adjournment Without End',
    emoji: '🕯️',
    description: 'Adjournment Without End extends the quiet work until the bog itself objects.',
    branch: 'filing',
    cost: 800,
    requires: 'filing-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineCap', addSeconds: 43200 }],
  },
  {
    id: 'hands-1-1',
    name: 'Copper Grip I',
    emoji: '🖐️',
    description: 'Copper Grip I teaches the thumb where the harvest button gives way.',
    branch: 'hands',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'click', factor: 1.25 }],
  },
  {
    id: 'hands-1-2',
    name: 'Copper Grip II',
    emoji: '🖐️',
    description: 'Copper Grip II turns a firm grip into a reliable measure of broth.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-1',
    effects: [{ kind: 'multiplier', target: 'click', factor: 1.5 }],
  },
  {
    id: 'hands-1-3',
    name: 'Copper Grip III',
    emoji: '🖐️',
    description: 'Copper Grip III keeps the hand steady through a long morning of clicks.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-1-2',
    effects: [{ kind: 'multiplier', target: 'click', factor: 2 }],
  },
  {
    id: 'hands-1-4',
    name: 'Copper Grip IV',
    emoji: '🖐️',
    description: 'Copper Grip IV makes each press land with the weight of a signed instruction.',
    branch: 'hands',
    cost: 8,
    requires: 'hands-1-3',
    effects: [{ kind: 'multiplier', target: 'click', factor: 3 }],
  },
  {
    id: 'hands-1-5',
    name: 'Copper Grip V',
    emoji: '🖐️',
    description: 'Copper Grip V lets practiced fingers move faster without losing the count.',
    branch: 'hands',
    cost: 13,
    requires: 'hands-1-4',
    effects: [{ kind: 'multiplier', target: 'click', factor: 5 }],
  },
  {
    id: 'hands-1-6',
    name: 'Copper Grip VI',
    emoji: '🖐️',
    description: 'Copper Grip VI puts the whole hand behind one exceptionally productive gesture.',
    branch: 'hands',
    cost: 21,
    requires: 'hands-1-5',
    effects: [{ kind: 'multiplier', target: 'click', factor: 7 }],
  },
  {
    id: 'hands-1-leaf-1',
    name: 'Brass Knuckle',
    emoji: '🖐️',
    description: 'Brass Knuckle gives the working hand one more useful edge.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 2 }],
  },
  {
    id: 'hands-1-leaf-2',
    name: 'Palm Authority',
    emoji: '🖐️',
    description: 'Palm Authority lets the palm settle an argument with the harvest button.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 3 }],
  },
  {
    id: 'hands-1-leaf-3',
    name: 'Grip of Record',
    emoji: '🖐️',
    description: 'Grip of Record makes a practiced grip count as official equipment.',
    branch: 'hands',
    cost: 3,
    requires: 'hands-1-6',
    effects: [{ kind: 'multiplier', target: 'click', factor: 5 }],
  },
  {
    id: 'hands-2-1',
    name: 'Field Rhythm I',
    emoji: '🖐️',
    description: 'Field Rhythm I sets a pace the peat cutter can hold without complaint.',
    branch: 'hands',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'fieldwork', factor: 1.25 }],
  },
  {
    id: 'hands-2-2',
    name: 'Field Rhythm II',
    emoji: '🖐️',
    description: 'Field Rhythm II makes fieldwork rewards arrive in a more orderly heap.',
    branch: 'hands',
    cost: 6,
    requires: 'hands-2-1',
    effects: [{ kind: 'fieldwork', factor: 1.5 }],
  },
  {
    id: 'hands-2-3',
    name: 'Field Rhythm III',
    emoji: '🖐️',
    description: 'Field Rhythm III keeps a wet glove from losing the useful part of the motion.',
    branch: 'hands',
    cost: 10,
    requires: 'hands-2-2',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-2-4',
    name: 'Field Rhythm IV',
    emoji: '🖐️',
    description: 'Field Rhythm IV turns a repeated cut into a dependable field practice.',
    branch: 'hands',
    cost: 16,
    requires: 'hands-2-3',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-2-5',
    name: 'Field Rhythm V',
    emoji: '🖐️',
    description: 'Field Rhythm V lets the cutter work quickly while the bog keeps its dignity.',
    branch: 'hands',
    cost: 26,
    requires: 'hands-2-4',
    effects: [{ kind: 'fieldwork', factor: 5 }],
  },
  {
    id: 'hands-2-6',
    name: 'Field Rhythm VI',
    emoji: '🖐️',
    description: 'Field Rhythm VI gives every field hand the rhythm of a favourable ruling.',
    branch: 'hands',
    cost: 42,
    requires: 'hands-2-5',
    effects: [{ kind: 'fieldwork', factor: 7 }],
  },
  {
    id: 'hands-2-leaf-1',
    name: 'Peat Measure',
    emoji: '🖐️',
    description: 'Peat Measure makes the cut worth measuring before the mud closes over it.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-2-6',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-2-leaf-2',
    name: 'Wetland Pace',
    emoji: '🖐️',
    description: 'Wetland Pace sets a pace the wetland can afford to reward.',
    branch: 'hands',
    cost: 5,
    requires: 'hands-2-6',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-3-1',
    name: 'Calibration Palm I',
    emoji: '🖐️',
    description: 'Calibration Palm I keeps the calibration hand centred on the useful middle.',
    branch: 'hands',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'fieldwork', factor: 1.25 }],
  },
  {
    id: 'hands-3-2',
    name: 'Calibration Palm II',
    emoji: '🖐️',
    description: 'Calibration Palm II makes a close reading pay better than a lucky guess.',
    branch: 'hands',
    cost: 10,
    requires: 'hands-3-1',
    effects: [{ kind: 'fieldwork', factor: 1.5 }],
  },
  {
    id: 'hands-3-3',
    name: 'Calibration Palm III',
    emoji: '🖐️',
    description: 'Calibration Palm III turns careful timing into compute and evidence in equal measure.',
    branch: 'hands',
    cost: 15,
    requires: 'hands-3-2',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-3-4',
    name: 'Calibration Palm IV',
    emoji: '🖐️',
    description: 'Calibration Palm IV lets the palm remember exactly where the target was.',
    branch: 'hands',
    cost: 25,
    requires: 'hands-3-3',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-3-5',
    name: 'Calibration Palm V',
    emoji: '🖐️',
    description: 'Calibration Palm V gives each calibration attempt a steadier administrative finish.',
    branch: 'hands',
    cost: 39,
    requires: 'hands-3-4',
    effects: [{ kind: 'fieldwork', factor: 5 }],
  },
  {
    id: 'hands-3-6',
    name: 'Calibration Palm VI',
    emoji: '🖐️',
    description: 'Calibration Palm VI puts the entire bench behind one immaculate reading.',
    branch: 'hands',
    cost: 63,
    requires: 'hands-3-5',
    effects: [{ kind: 'fieldwork', factor: 7 }],
  },
  {
    id: 'hands-3-leaf-1',
    name: 'True Centre',
    emoji: '🖐️',
    description: 'True Centre finds the centre before the needle has time to wander.',
    branch: 'hands',
    cost: 7,
    requires: 'hands-3-6',
    effects: [{ kind: 'fieldwork', factor: 2 }],
  },
  {
    id: 'hands-3-leaf-2',
    name: 'Steady Mark',
    emoji: '🖐️',
    description: 'Steady Mark leaves a steady mark where the calibration will find it.',
    branch: 'hands',
    cost: 7,
    requires: 'hands-3-6',
    effects: [{ kind: 'fieldwork', factor: 3 }],
  },
  {
    id: 'hands-4-1',
    name: 'Click Equity I',
    emoji: '🖐️',
    description: 'Click Equity I returns a little broth to the hand that earned it.',
    branch: 'hands',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.01 }],
  },
  {
    id: 'hands-4-2',
    name: 'Click Equity II',
    emoji: '🖐️',
    description: 'Click Equity II makes the harvest button share its proceeds more fairly.',
    branch: 'hands',
    cost: 13,
    requires: 'hands-4-1',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.02 }],
  },
  {
    id: 'hands-4-3',
    name: 'Click Equity III',
    emoji: '🖐️',
    description: 'Click Equity III turns repeated clicking into a modest evidence practice.',
    branch: 'hands',
    cost: 20,
    requires: 'hands-4-2',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.03 }],
  },
  {
    id: 'hands-4-4',
    name: 'Click Equity IV',
    emoji: '🖐️',
    description: 'Click Equity IV lets every useful press carry a second consequence.',
    branch: 'hands',
    cost: 33,
    requires: 'hands-4-3',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.04 }],
  },
  {
    id: 'hands-4-5',
    name: 'Click Equity V',
    emoji: '🖐️',
    description: 'Click Equity V keeps the click ledger balanced under heavy use.',
    branch: 'hands',
    cost: 52,
    requires: 'hands-4-4',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.05 }],
  },
  {
    id: 'hands-4-6',
    name: 'Click Equity VI',
    emoji: '🖐️',
    description: 'Click Equity VI gives the working hand its full and properly calculated dividend.',
    branch: 'hands',
    cost: 84,
    requires: 'hands-4-5',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.06 }],
  },
  {
    id: 'hands-4-leaf-1',
    name: 'Broth Rebate',
    emoji: '🖐️',
    description: 'Broth Rebate returns a small rebate before the next click arrives.',
    branch: 'hands',
    cost: 9,
    requires: 'hands-4-6',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.03 }],
  },
  {
    id: 'hands-4-leaf-2',
    name: 'Evidence Share',
    emoji: '🖐️',
    description: 'Evidence Share sets aside a fair share for the evidence desk.',
    branch: 'hands',
    cost: 9,
    requires: 'hands-4-6',
    effects: [{ kind: 'clickBrothFraction', fraction: 0.05 }],
  },
  {
    id: 'hands-capstone-1',
    name: 'Handwork Charter',
    emoji: '🖐️',
    description: 'Handwork Charter recognises the hand as the first machine in the marsh.',
    branch: 'hands',
    cost: 650,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'multiplier', target: 'click', factor: 7 }],
  },
  {
    id: 'hands-capstone-2',
    name: 'Field Hand Writ',
    emoji: '🖐️',
    description: 'Field Hand Writ makes every careful cut admissible as productive fieldwork.',
    branch: 'hands',
    cost: 725,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'fieldwork', factor: 1.8 }],
  },
  {
    id: 'hands-capstone-3',
    name: 'Palm Dividend',
    emoji: '🖐️',
    description: 'Palm Dividend settles the click ledger in favour of the person doing the clicking.',
    branch: 'hands',
    cost: 800,
    requires: 'hands-4-leaf-2',
    requiresAny: ['roots-1'],
    effects: [{ kind: 'clickBrothFraction', fraction: 0.10 }],
  },
  {
    id: 'engines-1-1',
    name: 'Broth Machinery I',
    emoji: '⚙️',
    description: 'Broth Machinery I keeps the broth line turning after the first kettle settles.',
    branch: 'engines',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 1.25 }],
  },
  {
    id: 'engines-1-2',
    name: 'Broth Machinery II',
    emoji: '⚙️',
    description: 'Broth Machinery II makes the harvester answer more cleanly to its own demand.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-1',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 1.5 }],
  },
  {
    id: 'engines-1-3',
    name: 'Broth Machinery III',
    emoji: '⚙️',
    description: 'Broth Machinery III puts a measured increase behind every warm production cycle.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-1-2',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'engines-1-4',
    name: 'Broth Machinery IV',
    emoji: '⚙️',
    description: 'Broth Machinery IV lets the broth machinery carry a heavier docket.',
    branch: 'engines',
    cost: 8,
    requires: 'engines-1-3',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 3 }],
  },
  {
    id: 'engines-1-5',
    name: 'Broth Machinery V',
    emoji: '⚙️',
    description: 'Broth Machinery V turns a serviceable line into the bogs preferred supplier.',
    branch: 'engines',
    cost: 13,
    requires: 'engines-1-4',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 5 }],
  },
  {
    id: 'engines-1-6',
    name: 'Broth Machinery VI',
    emoji: '⚙️',
    description: 'Broth Machinery VI gives the whole broth floor a formidable mechanical advantage.',
    branch: 'engines',
    cost: 21,
    requires: 'engines-1-5',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 7 }],
  },
  {
    id: 'engines-1-leaf-1',
    name: 'Kettle Allowance',
    emoji: '⚙️',
    description: 'Kettle Allowance grants the kettle room for one more useful turn.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 2 }],
  },
  {
    id: 'engines-1-leaf-2',
    name: 'Harvester Warrant',
    emoji: '⚙️',
    description: 'Harvester Warrant authorises the harvester to exceed its old brief.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 3 }],
  },
  {
    id: 'engines-1-leaf-3',
    name: 'Spare Bearing',
    emoji: '⚙️',
    description: 'Spare Bearing keeps the broth machinery turning through a long inspection.',
    branch: 'engines',
    cost: 3,
    requires: 'engines-1-6',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 5 }],
  },
  {
    id: 'engines-2-1',
    name: 'Cooling Estate I',
    emoji: '⚙️',
    description: 'Cooling Estate I gives the cooling line a little more room to breathe.',
    branch: 'engines',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'cooling', factor: 1.05 }],
  },
  {
    id: 'engines-2-2',
    name: 'Cooling Estate II',
    emoji: '⚙️',
    description: 'Cooling Estate II keeps the chillers ahead of a modest production dispute.',
    branch: 'engines',
    cost: 6,
    requires: 'engines-2-1',
    effects: [{ kind: 'cooling', factor: 1.1 }],
  },
  {
    id: 'engines-2-3',
    name: 'Cooling Estate III',
    emoji: '⚙️',
    description: 'Cooling Estate III turns spare coolant into a quiet thermal advantage.',
    branch: 'engines',
    cost: 10,
    requires: 'engines-2-2',
    effects: [{ kind: 'cooling', factor: 1.2 }],
  },
  {
    id: 'engines-2-4',
    name: 'Cooling Estate IV',
    emoji: '⚙️',
    description: 'Cooling Estate IV lets the cold side of the plant answer without delay.',
    branch: 'engines',
    cost: 16,
    requires: 'engines-2-3',
    effects: [{ kind: 'cooling', factor: 1.3 }],
  },
  {
    id: 'engines-2-5',
    name: 'Cooling Estate V',
    emoji: '⚙️',
    description: 'Cooling Estate V makes the cooling estate broad enough for another rack.',
    branch: 'engines',
    cost: 26,
    requires: 'engines-2-4',
    effects: [{ kind: 'cooling', factor: 1.4 }],
  },
  {
    id: 'engines-2-6',
    name: 'Cooling Estate VI',
    emoji: '⚙️',
    description: 'Cooling Estate VI puts the entire temperature ledger under excellent management.',
    branch: 'engines',
    cost: 42,
    requires: 'engines-2-5',
    effects: [{ kind: 'cooling', factor: 1.5 }],
  },
  {
    id: 'engines-2-leaf-1',
    name: 'Coolant Lease',
    emoji: '⚙️',
    description: 'Coolant Lease leases one more useful degree of calm to the plant.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-2-6',
    effects: [{ kind: 'cooling', factor: 1.2 }],
  },
  {
    id: 'engines-2-leaf-2',
    name: 'Chiller Easement',
    emoji: '⚙️',
    description: 'Chiller Easement gives the chiller an easement through the hottest hour.',
    branch: 'engines',
    cost: 5,
    requires: 'engines-2-6',
    effects: [{ kind: 'cooling', factor: 1.4 }],
  },
  {
    id: 'engines-3-1',
    name: 'Rack Ordinance I',
    emoji: '⚙️',
    description: 'Rack Ordinance I lowers the cost of a rack without lowering its standards.',
    branch: 'engines',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'costScale', line: 'broth', delta: -0.005 }],
  },
  {
    id: 'engines-3-2',
    name: 'Rack Ordinance II',
    emoji: '⚙️',
    description: 'Rack Ordinance II makes compute equipment answerable to a more sensible tariff.',
    branch: 'engines',
    cost: 10,
    requires: 'engines-3-1',
    effects: [{ kind: 'costScale', line: 'peat', delta: -0.008 }],
  },
  {
    id: 'engines-3-3',
    name: 'Rack Ordinance III',
    emoji: '⚙️',
    description: 'Rack Ordinance III puts the kettle line on a cheaper and sturdier footing.',
    branch: 'engines',
    cost: 15,
    requires: 'engines-3-2',
    effects: [{ kind: 'costScale', line: 'sphagnum', delta: -0.01 }],
  },
  {
    id: 'engines-3-4',
    name: 'Rack Ordinance IV',
    emoji: '⚙️',
    description: 'Rack Ordinance IV reduces the filing cost of machinery the bog already needs.',
    branch: 'engines',
    cost: 25,
    requires: 'engines-3-3',
    effects: [{ kind: 'costScale', line: 'methane', delta: -0.012 }],
  },
  {
    id: 'engines-3-5',
    name: 'Rack Ordinance V',
    emoji: '⚙️',
    description: 'Rack Ordinance V lets the production lines buy their next argument at a discount.',
    branch: 'engines',
    cost: 39,
    requires: 'engines-3-4',
    effects: [{ kind: 'costScale', line: 'briquettes', delta: -0.015 }],
  },
  {
    id: 'engines-3-6',
    name: 'Rack Ordinance VI',
    emoji: '⚙️',
    description: 'Rack Ordinance VI sets a broad cost precedent across the working plant.',
    branch: 'engines',
    cost: 63,
    requires: 'engines-3-5',
    effects: [{ kind: 'costScale', line: 'briquettes', delta: -0.02 }],
  },
  {
    id: 'engines-3-leaf-1',
    name: 'Fair Rack Price',
    emoji: '⚙️',
    description: 'Fair Rack Price sets a fair price on the next rack without touching the warranty.',
    branch: 'engines',
    cost: 7,
    requires: 'engines-3-6',
    effects: [{ kind: 'costScale', line: 'compute', delta: -0.01 }],
  },
  {
    id: 'engines-3-leaf-2',
    name: 'Copper Discount',
    emoji: '⚙️',
    description: 'Copper Discount finds a small discount in the copper accounts.',
    branch: 'engines',
    cost: 7,
    requires: 'engines-3-6',
    effects: [{ kind: 'costScale', line: 'broth', delta: -0.015 }],
  },
  {
    id: 'engines-4-1',
    name: 'Production Spine I',
    emoji: '⚙️',
    description: 'Production Spine I places the first free machine where the line can use it.',
    branch: 'engines',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'freeBuildings', buildingId: 'harvester', count: 1 }],
  },
  {
    id: 'engines-4-2',
    name: 'Production Spine II',
    emoji: '⚙️',
    description: 'Production Spine II adds an unbilled hand to the peat-side operation.',
    branch: 'engines',
    cost: 13,
    requires: 'engines-4-1',
    effects: [{ kind: 'freeBuildings', buildingId: 'peat-cutter', count: 2 }],
  },
  {
    id: 'engines-4-3',
    name: 'Production Spine III',
    emoji: '⚙️',
    description: 'Production Spine III gives the cooling floor one quiet unit of assistance.',
    branch: 'engines',
    cost: 20,
    requires: 'engines-4-2',
    effects: [{ kind: 'freeBuildings', buildingId: 'chiller', count: 3 }],
  },
  {
    id: 'engines-4-4',
    name: 'Production Spine IV',
    emoji: '⚙️',
    description: 'Production Spine IV sets a complimentary kettle beside the paid machinery.',
    branch: 'engines',
    cost: 33,
    requires: 'engines-4-3',
    effects: [{ kind: 'freeBuildings', buildingId: 'kettle', count: 4 }],
  },
  {
    id: 'engines-4-5',
    name: 'Production Spine V',
    emoji: '⚙️',
    description: 'Production Spine V puts another still on the books without charging the books.',
    branch: 'engines',
    cost: 52,
    requires: 'engines-4-4',
    effects: [{ kind: 'freeBuildings', buildingId: 'copper-still', count: 5 }],
  },
  {
    id: 'engines-4-6',
    name: 'Production Spine VI',
    emoji: '⚙️',
    description: 'Production Spine VI hands the supercomputer a final rack the ledger cannot invoice.',
    branch: 'engines',
    cost: 84,
    requires: 'engines-4-5',
    effects: [{ kind: 'freeBuildings', buildingId: 'bog-supercomputer', count: 6 }],
  },
  {
    id: 'engines-4-leaf-1',
    name: 'Courtesy Harvester',
    emoji: '⚙️',
    description: 'Courtesy Harvester places one courtesy harvester beside the first line.',
    branch: 'engines',
    cost: 9,
    requires: 'engines-4-6',
    effects: [{ kind: 'freeBuildings', buildingId: 'harvester', count: 2 }],
  },
  {
    id: 'engines-4-leaf-2',
    name: 'Unbilled Rack',
    emoji: '⚙️',
    description: 'Unbilled Rack leaves an unbilled rack humming after the purchase order closes.',
    branch: 'engines',
    cost: 9,
    requires: 'engines-4-6',
    effects: [{ kind: 'freeBuildings', buildingId: 'rack', count: 2 }],
  },
  {
    id: 'engines-capstone-1',
    name: 'Mechanical Settlement',
    emoji: '⚙️',
    description: 'Mechanical Settlement settles the plant accounts in favour of useful motion.',
    branch: 'engines',
    cost: 650,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'multiplier', target: 'all', factor: 1.5 }],
  },
  {
    id: 'engines-capstone-2',
    name: 'Cool Room Precedent',
    emoji: '⚙️',
    description: 'Cool Room Precedent makes a cool room the default condition for serious production.',
    branch: 'engines',
    cost: 725,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'cooling', factor: 1.8 }],
  },
  {
    id: 'engines-capstone-3',
    name: 'Machinery Without Invoice',
    emoji: '⚙️',
    description: 'Machinery Without Invoice puts the final machine on the floor without a final bill.',
    branch: 'engines',
    cost: 800,
    requires: 'engines-4-leaf-2',
    requiresAny: ['kindling-1'],
    effects: [{ kind: 'freeBuildings', buildingId: 'rack', count: 8 }],
  },
  {
    id: 'lamps-1-1',
    name: 'Midnight Office I',
    emoji: '🕯️',
    description: 'Midnight Office I keeps the midnight office open by one more careful percentage.',
    branch: 'lamps',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'offlineRate', add: 0.01 }],
  },
  {
    id: 'lamps-1-2',
    name: 'Midnight Office II',
    emoji: '🕯️',
    description: 'Midnight Office II lets the last clerk finish a page before sleep.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-1',
    effects: [{ kind: 'offlineRate', add: 0.02 }],
  },
  {
    id: 'lamps-1-3',
    name: 'Midnight Office III',
    emoji: '🕯️',
    description: 'Midnight Office III turns a dark desk into a modest production line.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-1-2',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'lamps-1-4',
    name: 'Midnight Office IV',
    emoji: '🕯️',
    description: 'Midnight Office IV makes the hour after closing count for something.',
    branch: 'lamps',
    cost: 8,
    requires: 'lamps-1-3',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'lamps-1-5',
    name: 'Midnight Office V',
    emoji: '🕯️',
    description: 'Midnight Office V keeps a patient lamp over every unattended figure.',
    branch: 'lamps',
    cost: 13,
    requires: 'lamps-1-4',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'lamps-1-6',
    name: 'Midnight Office VI',
    emoji: '🕯️',
    description: 'Midnight Office VI gives the night office a rate worthy of its paperwork.',
    branch: 'lamps',
    cost: 21,
    requires: 'lamps-1-5',
    effects: [{ kind: 'offlineRate', add: 0.06 }],
  },
  {
    id: 'lamps-1-leaf-1',
    name: 'Night Margin',
    emoji: '🕯️',
    description: 'Night Margin leaves a little production in the margin after dark.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.03 }],
  },
  {
    id: 'lamps-1-leaf-2',
    name: 'Moonlit Addendum',
    emoji: '🕯️',
    description: 'Moonlit Addendum adds one moonlit paragraph to the rate sheet.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.05 }],
  },
  {
    id: 'lamps-1-leaf-3',
    name: 'Third Watch',
    emoji: '🕯️',
    description: 'Third Watch leaves a lamp burning for the clerk who comes after midnight.',
    branch: 'lamps',
    cost: 3,
    requires: 'lamps-1-6',
    effects: [{ kind: 'offlineRate', add: 0.04 }],
  },
  {
    id: 'lamps-2-1',
    name: 'Moon Ledger I',
    emoji: '🕯️',
    description: 'Moon Ledger I keeps the moon ledger open through a longer absence.',
    branch: 'lamps',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'offlineCap', addSeconds: 1800 }],
  },
  {
    id: 'lamps-2-2',
    name: 'Moon Ledger II',
    emoji: '🕯️',
    description: 'Moon Ledger II adds another interval to the record of unattended work.',
    branch: 'lamps',
    cost: 6,
    requires: 'lamps-2-1',
    effects: [{ kind: 'offlineCap', addSeconds: 3600 }],
  },
  {
    id: 'lamps-2-3',
    name: 'Moon Ledger III',
    emoji: '🕯️',
    description: 'Moon Ledger III makes the night clerk willing to wait for the next return.',
    branch: 'lamps',
    cost: 10,
    requires: 'lamps-2-2',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'lamps-2-4',
    name: 'Moon Ledger IV',
    emoji: '🕯️',
    description: 'Moon Ledger IV stretches the ledger past the ordinary eight-hour courtesy.',
    branch: 'lamps',
    cost: 16,
    requires: 'lamps-2-3',
    effects: [{ kind: 'offlineCap', addSeconds: 10800 }],
  },
  {
    id: 'lamps-2-5',
    name: 'Moon Ledger V',
    emoji: '🕯️',
    description: 'Moon Ledger V gives a long absence enough room to remain productive.',
    branch: 'lamps',
    cost: 26,
    requires: 'lamps-2-4',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'lamps-2-6',
    name: 'Moon Ledger VI',
    emoji: '🕯️',
    description: 'Moon Ledger VI lets the moon ledger cover an entire respectable disappearance.',
    branch: 'lamps',
    cost: 42,
    requires: 'lamps-2-5',
    effects: [{ kind: 'offlineCap', addSeconds: 21600 }],
  },
  {
    id: 'lamps-2-leaf-1',
    name: 'Moon Extension',
    emoji: '🕯️',
    description: 'Moon Extension extends the moon ledger without disturbing its columns.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-2-6',
    effects: [{ kind: 'offlineCap', addSeconds: 7200 }],
  },
  {
    id: 'lamps-2-leaf-2',
    name: 'Night Interval',
    emoji: '🕯️',
    description: 'Night Interval keeps one more interval available to the absent keeper.',
    branch: 'lamps',
    cost: 5,
    requires: 'lamps-2-6',
    effects: [{ kind: 'offlineCap', addSeconds: 14400 }],
  },
  {
    id: 'lamps-3-1',
    name: 'Long Watch I',
    emoji: '🕯️',
    description: 'Long Watch I makes unattended production return with a little more weight.',
    branch: 'lamps',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'offlineMultiplier', factor: 1.1 }],
  },
  {
    id: 'lamps-3-2',
    name: 'Long Watch II',
    emoji: '🕯️',
    description: 'Long Watch II keeps the watchful part of the bog from being wasted.',
    branch: 'lamps',
    cost: 10,
    requires: 'lamps-3-1',
    effects: [{ kind: 'offlineMultiplier', factor: 1.2 }],
  },
  {
    id: 'lamps-3-3',
    name: 'Long Watch III',
    emoji: '🕯️',
    description: 'Long Watch III turns a long absence into a more generous report.',
    branch: 'lamps',
    cost: 15,
    requires: 'lamps-3-2',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'lamps-3-4',
    name: 'Long Watch IV',
    emoji: '🕯️',
    description: 'Long Watch IV lets the night shift retain its better work.',
    branch: 'lamps',
    cost: 25,
    requires: 'lamps-3-3',
    effects: [{ kind: 'offlineMultiplier', factor: 1.4 }],
  },
  {
    id: 'lamps-3-5',
    name: 'Long Watch V',
    emoji: '🕯️',
    description: 'Long Watch V gives the watch a yield the Magistrate can understand.',
    branch: 'lamps',
    cost: 39,
    requires: 'lamps-3-4',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'lamps-3-6',
    name: 'Long Watch VI',
    emoji: '🕯️',
    description: 'Long Watch VI returns the full dignity of a properly staffed night.',
    branch: 'lamps',
    cost: 63,
    requires: 'lamps-3-5',
    effects: [{ kind: 'offlineMultiplier', factor: 1.6 }],
  },
  {
    id: 'lamps-3-leaf-1',
    name: 'Watchmans Share',
    emoji: '🕯️',
    description: 'Watchmans Share returns the watchman a fairer share of the quiet yield.',
    branch: 'lamps',
    cost: 7,
    requires: 'lamps-3-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.3 }],
  },
  {
    id: 'lamps-3-leaf-2',
    name: 'Darkroom Yield',
    emoji: '🕯️',
    description: 'Darkroom Yield makes the darkroom hand back its most useful figures.',
    branch: 'lamps',
    cost: 7,
    requires: 'lamps-3-6',
    effects: [{ kind: 'offlineMultiplier', factor: 1.5 }],
  },
  {
    id: 'lamps-4-1',
    name: 'Closed Hours I',
    emoji: '🕯️',
    description: 'Closed Hours I keeps closed hours from becoming empty hours.',
    branch: 'lamps',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'offlineRate', add: 0.015 }],
  },
  {
    id: 'lamps-4-2',
    name: 'Closed Hours II',
    emoji: '🕯️',
    description: 'Closed Hours II puts a modest rate behind every locked door.',
    branch: 'lamps',
    cost: 13,
    requires: 'lamps-4-1',
    effects: [{ kind: 'offlineRate', add: 0.025 }],
  },
  {
    id: 'lamps-4-3',
    name: 'Closed Hours III',
    emoji: '🕯️',
    description: 'Closed Hours III makes absence a recognised condition of production.',
    branch: 'lamps',
    cost: 20,
    requires: 'lamps-4-2',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'lamps-4-4',
    name: 'Closed Hours IV',
    emoji: '🕯️',
    description: 'Closed Hours IV lets the lamps keep their promise after the keys turn.',
    branch: 'lamps',
    cost: 33,
    requires: 'lamps-4-3',
    effects: [{ kind: 'offlineRate', add: 0.045 }],
  },
  {
    id: 'lamps-4-5',
    name: 'Closed Hours V',
    emoji: '🕯️',
    description: 'Closed Hours V gives the quiet shift a longer and steadier reach.',
    branch: 'lamps',
    cost: 52,
    requires: 'lamps-4-4',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'lamps-4-6',
    name: 'Closed Hours VI',
    emoji: '🕯️',
    description: 'Closed Hours VI keeps the whole closed court producing beneath its seal.',
    branch: 'lamps',
    cost: 84,
    requires: 'lamps-4-5',
    effects: [{ kind: 'offlineRate', add: 0.065 }],
  },
  {
    id: 'lamps-4-leaf-1',
    name: 'Locked Door Rate',
    emoji: '🕯️',
    description: 'Locked Door Rate keeps one locked door on the production ledger.',
    branch: 'lamps',
    cost: 9,
    requires: 'lamps-4-6',
    effects: [{ kind: 'offlineRate', add: 0.035 }],
  },
  {
    id: 'lamps-4-leaf-2',
    name: 'After Bell',
    emoji: '🕯️',
    description: 'After Bell lets the after-bell work continue without a witness.',
    branch: 'lamps',
    cost: 9,
    requires: 'lamps-4-6',
    effects: [{ kind: 'offlineRate', add: 0.055 }],
  },
  {
    id: 'lamps-capstone-1',
    name: 'Lamp Parliament',
    emoji: '🕯️',
    description: 'Lamp Parliament gives the night lamps a majority over every empty hour.',
    branch: 'lamps',
    cost: 650,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineRate', add: 0.08 }],
  },
  {
    id: 'lamps-capstone-2',
    name: 'Watch Kept',
    emoji: '🕯️',
    description: 'Watch Kept records that the watch was kept even when nobody looked.',
    branch: 'lamps',
    cost: 725,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineMultiplier', factor: 1.8 }],
  },
  {
    id: 'lamps-capstone-3',
    name: 'Night Without Adjournment',
    emoji: '🕯️',
    description: 'Night Without Adjournment leaves the office open until the bog decides otherwise.',
    branch: 'lamps',
    cost: 800,
    requires: 'lamps-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'offlineCap', addSeconds: 43200 }],
  },
  {
    id: 'stills-1-1',
    name: 'Sludge Alchemy I',
    emoji: '⚗️',
    description: 'Sludge Alchemy I teaches the sludge line to ask less of its input.',
    branch: 'stills',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.98 }],
  },
  {
    id: 'stills-1-2',
    name: 'Sludge Alchemy II',
    emoji: '⚗️',
    description: 'Sludge Alchemy II keeps the first conversion from spilling useful broth.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-1',
    effects: [{ kind: 'converterEfficiency', line: 'peat', factor: 0.95 }],
  },
  {
    id: 'stills-1-3',
    name: 'Sludge Alchemy III',
    emoji: '⚗️',
    description: 'Sludge Alchemy III makes a thick residue answer to a thinner instruction.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-1-2',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.90 }],
  },
  {
    id: 'stills-1-4',
    name: 'Sludge Alchemy IV',
    emoji: '⚗️',
    description: 'Sludge Alchemy IV turns the still room waste into a more agreeable feed.',
    branch: 'stills',
    cost: 8,
    requires: 'stills-1-3',
    effects: [{ kind: 'converterEfficiency', line: 'methane', factor: 0.85 }],
  },
  {
    id: 'stills-1-5',
    name: 'Sludge Alchemy V',
    emoji: '⚗️',
    description: 'Sludge Alchemy V lets the sludge line run with a careful economy.',
    branch: 'stills',
    cost: 13,
    requires: 'stills-1-4',
    effects: [{ kind: 'converterEfficiency', line: 'compute', factor: 0.80 }],
  },
  {
    id: 'stills-1-6',
    name: 'Sludge Alchemy VI',
    emoji: '⚗️',
    description: 'Sludge Alchemy VI gives every dark vat the efficiency of a seasoned clerk.',
    branch: 'stills',
    cost: 21,
    requires: 'stills-1-5',
    effects: [{ kind: 'converterEfficiency', line: 'briquettes', factor: 0.75 }],
  },
  {
    id: 'stills-1-leaf-1',
    name: 'Dark Vat Allowance',
    emoji: '⚗️',
    description: 'Dark Vat Allowance allows the dark vat to keep its best feedstock.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.90 }],
  },
  {
    id: 'stills-1-leaf-2',
    name: 'Residue Economy',
    emoji: '⚗️',
    description: 'Residue Economy finds economy in residue that used to be swept aside.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.82 }],
  },
  {
    id: 'stills-1-leaf-3',
    name: 'Clear Distillate',
    emoji: '⚗️',
    description: 'Clear Distillate leaves the first retort cleaner than the docket expected.',
    branch: 'stills',
    cost: 3,
    requires: 'stills-1-6',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.88 }],
  },
  {
    id: 'stills-2-1',
    name: 'Refining Bench I',
    emoji: '⚗️',
    description: 'Refining Bench I gives sludge a cleaner path toward the next useful form.',
    branch: 'stills',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'multiplier', target: 'sludge', factor: 1.25 }],
  },
  {
    id: 'stills-2-2',
    name: 'Refining Bench II',
    emoji: '⚗️',
    description: 'Refining Bench II lets briquettes arrive at the bench with fewer complaints.',
    branch: 'stills',
    cost: 6,
    requires: 'stills-2-1',
    effects: [{ kind: 'multiplier', target: 'briquettes', factor: 1.5 }],
  },
  {
    id: 'stills-2-3',
    name: 'Refining Bench III',
    emoji: '⚗️',
    description: 'Refining Bench III makes refined broth answer more promptly to the still.',
    branch: 'stills',
    cost: 10,
    requires: 'stills-2-2',
    effects: [{ kind: 'multiplier', target: 'refinedBroth', factor: 2 }],
  },
  {
    id: 'stills-2-4',
    name: 'Refining Bench IV',
    emoji: '⚗️',
    description: 'Refining Bench IV turns sediment into a resource the clerk can pronounce.',
    branch: 'stills',
    cost: 16,
    requires: 'stills-2-3',
    effects: [{ kind: 'multiplier', target: 'sediment', factor: 3 }],
  },
  {
    id: 'stills-2-5',
    name: 'Refining Bench V',
    emoji: '⚗️',
    description: 'Refining Bench V puts essence within reach of an ordinary production day.',
    branch: 'stills',
    cost: 26,
    requires: 'stills-2-4',
    effects: [{ kind: 'multiplier', target: 'essence', factor: 5 }],
  },
  {
    id: 'stills-2-6',
    name: 'Refining Bench VI',
    emoji: '⚗️',
    description: 'Refining Bench VI returns the entire chain to the bench polished and ready.',
    branch: 'stills',
    cost: 42,
    requires: 'stills-2-5',
    effects: [{ kind: 'multiplier', target: 'broth', factor: 7 }],
  },
  {
    id: 'stills-2-leaf-1',
    name: 'Clean Retort',
    emoji: '⚗️',
    description: 'Clean Retort keeps a clean retort between the sludge and the books.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-2-6',
    effects: [{ kind: 'multiplier', target: 'sludge', factor: 3 }],
  },
  {
    id: 'stills-2-leaf-2',
    name: 'Bright Filtrate',
    emoji: '⚗️',
    description: 'Bright Filtrate finds a brighter filtrate hiding in the ordinary run.',
    branch: 'stills',
    cost: 5,
    requires: 'stills-2-6',
    effects: [{ kind: 'multiplier', target: 'essence', factor: 5 }],
  },
  {
    id: 'stills-3-1',
    name: 'Sediment Method I',
    emoji: '⚗️',
    description: 'Sediment Method I lets the still line leave something useful behind.',
    branch: 'stills',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.02 }],
  },
  {
    id: 'stills-3-2',
    name: 'Sediment Method II',
    emoji: '⚗️',
    description: 'Sediment Method II turns a settled layer into a documented secondary yield.',
    branch: 'stills',
    cost: 10,
    requires: 'stills-3-1',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.03 }],
  },
  {
    id: 'stills-3-3',
    name: 'Sediment Method III',
    emoji: '⚗️',
    description: 'Sediment Method III makes each refinement worth checking twice.',
    branch: 'stills',
    cost: 15,
    requires: 'stills-3-2',
    effects: [{ kind: 'byproduct', line: 'briquettes', resource: 'sludge', fraction: 0.04 }],
  },
  {
    id: 'stills-3-4',
    name: 'Sediment Method IV',
    emoji: '⚗️',
    description: 'Sediment Method IV keeps sediment from being treated as a clerical error.',
    branch: 'stills',
    cost: 25,
    requires: 'stills-3-3',
    effects: [{ kind: 'byproduct', line: 'refinedBroth', resource: 'essence', fraction: 0.05 }],
  },
  {
    id: 'stills-3-5',
    name: 'Sediment Method V',
    emoji: '⚗️',
    description: 'Sediment Method V gives residue a place in the production settlement.',
    branch: 'stills',
    cost: 39,
    requires: 'stills-3-4',
    effects: [{ kind: 'byproduct', line: 'sediment', resource: 'refinedBroth', fraction: 0.06 }],
  },
  {
    id: 'stills-3-6',
    name: 'Sediment Method VI',
    emoji: '⚗️',
    description: 'Sediment Method VI lets every still discharge a useful footnote to the run.',
    branch: 'stills',
    cost: 63,
    requires: 'stills-3-5',
    effects: [{ kind: 'byproduct', line: 'essence', resource: 'sludge', fraction: 0.08 }],
  },
  {
    id: 'stills-3-leaf-1',
    name: 'Settled Yield',
    emoji: '⚗️',
    description: 'Settled Yield adds a settled yield to the line that made it.',
    branch: 'stills',
    cost: 7,
    requires: 'stills-3-6',
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.05 }],
  },
  {
    id: 'stills-3-leaf-2',
    name: 'Second Pour',
    emoji: '⚗️',
    description: 'Second Pour keeps a second pour from going quietly to waste.',
    branch: 'stills',
    cost: 7,
    requires: 'stills-3-6',
    effects: [{ kind: 'byproduct', line: 'refinedBroth', resource: 'essence', fraction: 0.07 }],
  },
  {
    id: 'stills-4-1',
    name: 'Essence Practice I',
    emoji: '⚗️',
    description: 'Essence Practice I keeps the essence line from spending more than its recipe.',
    branch: 'stills',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'converterEfficiency', line: 'refinedBroth', factor: 0.97 }],
  },
  {
    id: 'stills-4-2',
    name: 'Essence Practice II',
    emoji: '⚗️',
    description: 'Essence Practice II makes refined broth a calmer input to the final still.',
    branch: 'stills',
    cost: 13,
    requires: 'stills-4-1',
    effects: [{ kind: 'converterEfficiency', line: 'sediment', factor: 0.94 }],
  },
  {
    id: 'stills-4-3',
    name: 'Essence Practice III',
    emoji: '⚗️',
    description: 'Essence Practice III lets sediment cross the bench with less resistance.',
    branch: 'stills',
    cost: 20,
    requires: 'stills-4-2',
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.90 }],
  },
  {
    id: 'stills-4-4',
    name: 'Essence Practice IV',
    emoji: '⚗️',
    description: 'Essence Practice IV turns a difficult conversion into a repeatable practice.',
    branch: 'stills',
    cost: 33,
    requires: 'stills-4-3',
    effects: [{ kind: 'converterEfficiency', line: 'broth', factor: 0.86 }],
  },
  {
    id: 'stills-4-5',
    name: 'Essence Practice V',
    emoji: '⚗️',
    description: 'Essence Practice V gives the essence room to accumulate without fuss.',
    branch: 'stills',
    cost: 52,
    requires: 'stills-4-4',
    effects: [{ kind: 'converterEfficiency', line: 'peat', factor: 0.82 }],
  },
  {
    id: 'stills-4-6',
    name: 'Essence Practice VI',
    emoji: '⚗️',
    description: 'Essence Practice VI puts the still room at the height of its own method.',
    branch: 'stills',
    cost: 84,
    requires: 'stills-4-5',
    effects: [{ kind: 'converterEfficiency', line: 'sphagnum', factor: 0.78 }],
  },
  {
    id: 'stills-4-leaf-1',
    name: 'Final Retort',
    emoji: '⚗️',
    description: 'Final Retort keeps the final retort within its written allowance.',
    branch: 'stills',
    cost: 9,
    requires: 'stills-4-6',
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.82 }],
  },
  {
    id: 'stills-4-leaf-2',
    name: 'Stillroom Discipline',
    emoji: '⚗️',
    description: 'Stillroom Discipline makes discipline the strongest ingredient in the room.',
    branch: 'stills',
    cost: 9,
    requires: 'stills-4-6',
    effects: [{ kind: 'converterEfficiency', line: 'refinedBroth', factor: 0.80 }],
  },
  {
    id: 'stills-capstone-1',
    name: 'Grand Retort',
    emoji: '⚗️',
    description: 'Grand Retort gives the still room one final and unusually patient hearing.',
    branch: 'stills',
    cost: 650,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'multiplier', target: 'essence', factor: 7 }],
  },
  {
    id: 'stills-capstone-2',
    name: 'Residue Concord',
    emoji: '⚗️',
    description: 'Residue Concord settles every useful byproduct before it reaches the drain.',
    branch: 'stills',
    cost: 725,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'byproduct', line: 'sphagnum', resource: 'sediment', fraction: 0.12 }],
  },
  {
    id: 'stills-capstone-3',
    name: 'Master of Stills',
    emoji: '⚗️',
    description: 'Master of Stills puts the whole conversion chain under one steady hand.',
    branch: 'stills',
    cost: 800,
    requires: 'stills-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'converterEfficiency', line: 'essence', factor: 0.70 }],
  },
  {
    id: 'keepers-1-1',
    name: 'Pierre\'s Furrow I',
    emoji: '🔮',
    description: 'Pierre\'s Furrow I keeps Pierre’s first furrow attached to every claimed quest.',
    branch: 'keepers',
    cost: 2,
    requires: 'seal',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.01, cap: 1.1 }],
  },
  {
    id: 'keepers-1-2',
    name: 'Pierre\'s Furrow II',
    emoji: '🔮',
    description: 'Pierre\'s Furrow II makes Pierre’s careful line of work count twice in the ledger.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-1',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.015, cap: 1.15 }],
  },
  {
    id: 'keepers-1-3',
    name: 'Pierre\'s Furrow III',
    emoji: '🔮',
    description: 'Pierre\'s Furrow III lets an old furrow answer a new settlement question.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-1-2',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.02, cap: 1.2 }],
  },
  {
    id: 'keepers-1-4',
    name: 'Pierre\'s Furrow IV',
    emoji: '🔮',
    description: 'Pierre\'s Furrow IV turns Pierre’s patience into a measurable production advantage.',
    branch: 'keepers',
    cost: 8,
    requires: 'keepers-1-3',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.025, cap: 1.25 }],
  },
  {
    id: 'keepers-1-5',
    name: 'Pierre\'s Furrow V',
    emoji: '🔮',
    description: 'Pierre\'s Furrow V gives the furrow enough reach to cross another wet season.',
    branch: 'keepers',
    cost: 13,
    requires: 'keepers-1-4',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.03, cap: 1.3 }],
  },
  {
    id: 'keepers-1-6',
    name: 'Pierre\'s Furrow VI',
    emoji: '🔮',
    description: 'Pierre\'s Furrow VI leaves Pierre’s work standing at the edge of the whole docket.',
    branch: 'keepers',
    cost: 21,
    requires: 'keepers-1-5',
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.035, cap: 1.4 }],
  },
  {
    id: 'keepers-1-leaf-1',
    name: 'Pierre’s Spare Furrow',
    emoji: '🔮',
    description: 'Pierre’s Spare Furrow keeps one spare furrow ready for the next quest.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'broth', perUnit: 0.03, cap: 1.2 }],
  },
  {
    id: 'keepers-1-leaf-2',
    name: 'Pierre’s Wet Acre',
    emoji: '🔮',
    description: 'Pierre’s Wet Acre lets a wet acre pay its debt to the quest book.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'peat', perUnit: 0.04, cap: 1.3 }],
  },
  {
    id: 'keepers-1-leaf-3',
    name: 'LLP Exhibit',
    emoji: '🔮',
    description: 'LLP Exhibit places one useful filing beside Pierre’s oldest furrow.',
    branch: 'keepers',
    cost: 3,
    requires: 'keepers-1-6',
    effects: [{ kind: 'perQuest', target: 'evidence', perUnit: 0.03, cap: 1.2 }],
  },
  {
    id: 'keepers-2-1',
    name: 'Shrome\'s Thread I',
    emoji: '🔮',
    description: 'Shrome\'s Thread I keeps Shrome’s thread running through every finished achievement.',
    branch: 'keepers',
    cost: 4,
    requires: 'seal',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.005, cap: 1.05 }],
  },
  {
    id: 'keepers-2-2',
    name: 'Shrome\'s Thread II',
    emoji: '🔮',
    description: 'Shrome\'s Thread II makes a completed mark useful beyond the day it was earned.',
    branch: 'keepers',
    cost: 6,
    requires: 'keepers-2-1',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.008, cap: 1.08 }],
  },
  {
    id: 'keepers-2-3',
    name: 'Shrome\'s Thread III',
    emoji: '🔮',
    description: 'Shrome\'s Thread III lets the thread tie one small victory to the next.',
    branch: 'keepers',
    cost: 10,
    requires: 'keepers-2-2',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.01, cap: 1.12 }],
  },
  {
    id: 'keepers-2-4',
    name: 'Shrome\'s Thread IV',
    emoji: '🔮',
    description: 'Shrome\'s Thread IV turns Shrome’s careful stitching into a broader reward.',
    branch: 'keepers',
    cost: 16,
    requires: 'keepers-2-3',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.012, cap: 1.16 }],
  },
  {
    id: 'keepers-2-5',
    name: 'Shrome\'s Thread V',
    emoji: '🔮',
    description: 'Shrome\'s Thread V gives the achievement ledger a thread it cannot misplace.',
    branch: 'keepers',
    cost: 26,
    requires: 'keepers-2-4',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.015, cap: 1.2 }],
  },
  {
    id: 'keepers-2-6',
    name: 'Shrome\'s Thread VI',
    emoji: '🔮',
    description: 'Shrome\'s Thread VI leaves Shrome’s work holding the entire record together.',
    branch: 'keepers',
    cost: 42,
    requires: 'keepers-2-5',
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.02, cap: 1.3 }],
  },
  {
    id: 'keepers-2-leaf-1',
    name: 'Shrome’s Knot',
    emoji: '🔮',
    description: 'Shrome’s Knot ties one more finished achievement into the working record.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-2-6',
    effects: [{ kind: 'perAchievement', target: 'compute', perUnit: 0.015, cap: 1.2 }],
  },
  {
    id: 'keepers-2-leaf-2',
    name: 'Threaded Medal',
    emoji: '🔮',
    description: 'Threaded Medal keeps a medal useful after the applause has stopped.',
    branch: 'keepers',
    cost: 5,
    requires: 'keepers-2-6',
    effects: [{ kind: 'perAchievement', target: 'evidence', perUnit: 0.02, cap: 1.3 }],
  },
  {
    id: 'keepers-3-1',
    name: 'Samkals\'s Shelf I',
    emoji: '🔮',
    description: 'Samkals\'s Shelf I keeps Samkals’s shelf moving at the speed of a settled question.',
    branch: 'keepers',
    cost: 6,
    requires: 'seal',
    effects: [{ kind: 'researchSpeed', factor: 1.05 }],
  },
  {
    id: 'keepers-3-2',
    name: 'Samkals\'s Shelf II',
    emoji: '🔮',
    description: 'Samkals\'s Shelf II puts one more reference within the researchers’ reach.',
    branch: 'keepers',
    cost: 10,
    requires: 'keepers-3-1',
    effects: [{ kind: 'researchSpeed', factor: 1.1 }],
  },
  {
    id: 'keepers-3-3',
    name: 'Samkals\'s Shelf III',
    emoji: '🔮',
    description: 'Samkals\'s Shelf III lets the shelf carry a deeper stack of unfinished work.',
    branch: 'keepers',
    cost: 15,
    requires: 'keepers-3-2',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'keepers-3-4',
    name: 'Samkals\'s Shelf IV',
    emoji: '🔮',
    description: 'Samkals\'s Shelf IV turns Samkals’s filing discipline into research time saved.',
    branch: 'keepers',
    cost: 25,
    requires: 'keepers-3-3',
    effects: [{ kind: 'researchSpeed', factor: 1.3 }],
  },
  {
    id: 'keepers-3-5',
    name: 'Samkals\'s Shelf V',
    emoji: '🔮',
    description: 'Samkals\'s Shelf V gives every useful volume a clearer place in the queue.',
    branch: 'keepers',
    cost: 39,
    requires: 'keepers-3-4',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'keepers-3-6',
    name: 'Samkals\'s Shelf VI',
    emoji: '🔮',
    description: 'Samkals\'s Shelf VI leaves the whole research room indexed under Samkals’s eye.',
    branch: 'keepers',
    cost: 63,
    requires: 'keepers-3-5',
    effects: [{ kind: 'researchSpeed', factor: 1.5 }],
  },
  {
    id: 'keepers-3-leaf-1',
    name: 'Samkals’s Bookmark',
    emoji: '🔮',
    description: 'Samkals’s Bookmark marks the page where the next useful answer begins.',
    branch: 'keepers',
    cost: 7,
    requires: 'keepers-3-6',
    effects: [{ kind: 'researchSpeed', factor: 1.2 }],
  },
  {
    id: 'keepers-3-leaf-2',
    name: 'Shelf Precedent',
    emoji: '🔮',
    description: 'Shelf Precedent makes a well-kept shelf a precedent for speed.',
    branch: 'keepers',
    cost: 7,
    requires: 'keepers-3-6',
    effects: [{ kind: 'researchSpeed', factor: 1.4 }],
  },
  {
    id: 'keepers-4-1',
    name: 'McFly\'s Filing I',
    emoji: '🔮',
    description: 'McFly\'s Filing I keeps McFly and Chronicler LLP’s filing on the correct side of history.',
    branch: 'keepers',
    cost: 8,
    requires: 'seal',
    effects: [{ kind: 'starting', resource: 'broth', amount: 100 }],
  },
  {
    id: 'keepers-4-2',
    name: 'McFly\'s Filing II',
    emoji: '🔮',
    description: 'McFly\'s Filing II gives the LLP one more broth reserve before the next drainage.',
    branch: 'keepers',
    cost: 13,
    requires: 'keepers-4-1',
    effects: [{ kind: 'starting', resource: 'peat', amount: 250 }],
  },
  {
    id: 'keepers-4-3',
    name: 'McFly\'s Filing III',
    emoji: '🔮',
    description: 'McFly\'s Filing III turns a Sector 4 filing into a modest starting advantage.',
    branch: 'keepers',
    cost: 20,
    requires: 'keepers-4-2',
    effects: [{ kind: 'starting', resource: 'compute', amount: 500 }],
  },
  {
    id: 'keepers-4-4',
    name: 'McFly\'s Filing IV',
    emoji: '🔮',
    description: 'McFly\'s Filing IV lets the Magistrate find the LLP’s useful clause immediately.',
    branch: 'keepers',
    cost: 33,
    requires: 'keepers-4-3',
    effects: [{ kind: 'starting', resource: 'evidence', amount: 1000 }],
  },
  {
    id: 'keepers-4-5',
    name: 'McFly\'s Filing V',
    emoji: '🔮',
    description: 'McFly\'s Filing V makes every return begin with the paperwork already warm.',
    branch: 'keepers',
    cost: 52,
    requires: 'keepers-4-4',
    effects: [{ kind: 'coreGain', factor: 1.3 }],
  },
  {
    id: 'keepers-4-6',
    name: 'McFly\'s Filing VI',
    emoji: '🔮',
    description: 'McFly\'s Filing VI leaves McFly and Chronicler LLP’s signature beneath the whole settlement.',
    branch: 'keepers',
    cost: 84,
    requires: 'keepers-4-5',
    effects: [{ kind: 'coreGain', factor: 1.4 }],
  },
  {
    id: 'keepers-4-leaf-1',
    name: 'LLP Retainer',
    emoji: '🔮',
    description: 'LLP Retainer keeps a retainer of broth ready for the next run.',
    branch: 'keepers',
    cost: 9,
    requires: 'keepers-4-6',
    effects: [{ kind: 'starting', resource: 'broth', amount: 500 }],
  },
  {
    id: 'keepers-4-leaf-2',
    name: 'Sector Four Clause',
    emoji: '🔮',
    description: 'Sector Four Clause brings one useful Sector 4 clause into the new run.',
    branch: 'keepers',
    cost: 9,
    requires: 'keepers-4-6',
    effects: [{ kind: 'starting', resource: 'compute', amount: 1000 }],
  },
  {
    id: 'keepers-capstone-1',
    name: 'Pierre’s Final Furrow',
    emoji: '🔮',
    description: 'Pierre’s Final Furrow lets Pierre’s furrow run beneath every quest still to be claimed.',
    branch: 'keepers',
    cost: 650,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'perQuest', target: 'all', perUnit: 0.05, cap: 1.5 }],
  },
  {
    id: 'keepers-capstone-2',
    name: 'Shrome’s Binding Thread',
    emoji: '🔮',
    description: 'Shrome’s Binding Thread binds every achievement into one unusually durable reward.',
    branch: 'keepers',
    cost: 725,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'perAchievement', target: 'all', perUnit: 0.03, cap: 1.4 }],
  },
  {
    id: 'keepers-capstone-3',
    name: 'McFly’s Counterseal',
    emoji: '🔮',
    description: 'McFly’s Counterseal sets the LLP counterseal beside the Magistrate’s original wax.',
    branch: 'keepers',
    cost: 800,
    requires: 'keepers-4-leaf-2',
    requiresAny: ['hands-1-1'],
    effects: [{ kind: 'coreGain', factor: 1.6 }],
  },
];
